// Generated by CIRCT firtool-1.75.0
module Arbiter2_ScratchpadReadReq(	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  output        io_in_0_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [11:0] io_in_0_bits_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [11:0] io_in_1_bits_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_out_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output        io_out_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [11:0] io_out_bits_addr	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
);

  assign io_in_0_ready = io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  assign io_out_valid = io_in_0_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  assign io_out_bits_addr = io_in_0_valid ? io_in_0_bits_addr : io_in_1_bits_addr;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19]
endmodule

