// Generated by CIRCT firtool-1.75.0
module BankBinder(	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [4:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [4:0]  auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [4:0]  auto_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [4:0]  auto_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  TLMonitor_40 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (auto_out_a_ready),
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (auto_out_d_valid),
    .io_in_d_bits_opcode  (auto_out_d_bits_opcode),
    .io_in_d_bits_param   (auto_out_d_bits_param),
    .io_in_d_bits_size    (auto_out_d_bits_size),
    .io_in_d_bits_source  (auto_out_d_bits_source),
    .io_in_d_bits_sink    (auto_out_d_bits_sink),
    .io_in_d_bits_denied  (auto_out_d_bits_denied),
    .io_in_d_bits_corrupt (auto_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  assign auto_in_a_ready = auto_out_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_valid = auto_out_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_bits_opcode = auto_out_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_bits_param = auto_out_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_bits_size = auto_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_bits_source = auto_out_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_bits_denied = auto_out_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_bits_data = auto_out_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_in_d_bits_corrupt = auto_out_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_valid = auto_in_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_opcode = auto_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_param = auto_in_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_size = auto_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_source = auto_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_address = auto_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_mask = auto_in_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_data = auto_in_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_a_bits_corrupt = auto_in_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
  assign auto_out_d_ready = auto_in_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:61:9]
endmodule

