// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FrontendTLB(	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
  input         io_clients_0_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [39:0] io_clients_0_req_bits_tlb_req_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_clients_0_req_bits_tlb_req_passthrough,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_clients_0_req_bits_status_debug,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_clients_0_req_bits_status_mxr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_clients_0_resp_miss,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output [31:0] io_clients_0_resp_paddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_clients_1_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [39:0] io_clients_1_req_bits_tlb_req_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_clients_1_req_bits_status_debug,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_clients_1_req_bits_status_mxr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_clients_1_resp_miss,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output [31:0] io_clients_1_resp_paddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_ptw_0_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output [26:0] io_ptw_0_req_bits_bits_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_ptw_0_req_bits_bits_need_gpa,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_valid,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_ae_ptw,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_ae_final,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pf,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_gf,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_hr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_hw,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_hx,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [43:0] io_ptw_0_resp_bits_pte_ppn,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_d,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_g,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_u,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_pte_v,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_resp_bits_level,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_resp_bits_homogeneous,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [3:0]  io_ptw_0_ptbr_mode,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_0_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_0_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_0_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_0_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_0_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_0_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_0_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_1_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_1_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_1_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_1_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_1_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_1_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_1_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_2_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_2_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_2_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_2_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_2_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_2_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_2_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_3_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_3_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_3_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_3_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_3_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_3_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_3_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_4_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_4_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_4_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_4_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_4_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_4_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_4_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_5_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_5_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_5_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_5_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_5_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_5_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_5_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_6_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_6_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_6_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_6_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_6_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_6_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_6_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_7_cfg_l,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [1:0]  io_ptw_0_pmp_7_cfg_a,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_7_cfg_x,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_7_cfg_w,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_ptw_0_pmp_7_cfg_r,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [29:0] io_ptw_0_pmp_7_addr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input  [31:0] io_ptw_0_pmp_7_mask,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_exp_0_interrupt,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_exp_0_flush_retry,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  input         io_exp_0_flush_skip,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_counter_event_signal_15,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_counter_event_signal_16,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
  output        io_counter_event_signal_17	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:95:14]
);

  reg         tlbArbOpt_io_in_1_valid_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:130:27]
  reg         tlbArbOpt_io_in_0_valid_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:130:27]
  wire        _tlbArbOpt_io_in_0_ready;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire        _tlbArbOpt_io_in_1_ready;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire        _tlbArbOpt_io_out_valid;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire [39:0] _tlbArbOpt_io_out_bits_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire        _tlbArbOpt_io_out_bits_tlb_req_passthrough;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire [4:0]  _tlbArbOpt_io_out_bits_tlb_req_cmd;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire        _tlbArbOpt_io_out_bits_status_debug;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire        _tlbArbOpt_io_out_bits_status_mxr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  wire        _tlbs_0_io_resp_miss;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39]
  wire [31:0] _tlbs_0_io_resp_paddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39]
  reg         last_translated_valid;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:118:40]
  reg  [38:0] last_translated_vpn;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:119:38]
  reg  [31:0] last_translated_ppn;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:120:38]
  wire        tlbReqFire = _tlbArbOpt_io_in_0_ready & tlbArbOpt_io_in_0_valid_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50, :130:27, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [39:0] tlbArbOpt_io_in_0_bits_REG_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
  reg         tlbArbOpt_io_in_0_bits_REG_tlb_req_passthrough;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
  reg         tlbArbOpt_io_in_0_bits_REG_status_debug;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
  reg         tlbArbOpt_io_in_0_bits_REG_status_mxr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
  reg  [31:0] io_clients_0_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:147:35]
  reg         io_clients_0_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:148:35]
  reg         last_translated_valid_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:118:40]
  reg  [38:0] last_translated_vpn_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:119:38]
  reg  [31:0] last_translated_ppn_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:120:38]
  wire        tlbReqFire_1 = _tlbArbOpt_io_in_1_ready & tlbArbOpt_io_in_1_valid_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50, :130:27, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [39:0] tlbArbOpt_io_in_1_bits_REG_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
  reg         tlbArbOpt_io_in_1_bits_REG_status_debug;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
  reg         tlbArbOpt_io_in_1_bits_REG_status_mxr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
  reg  [31:0] io_clients_1_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:147:35]
  reg         io_clients_1_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:148:35]
  wire        _GEN = tlbReqFire & ~_tlbs_0_io_resp_miss;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39, :133:{22,25}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_0 = io_exp_0_flush_retry | io_exp_0_flush_skip;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:25:49]
  wire        _GEN_1 = tlbReqFire_1 & ~_tlbs_0_io_resp_miss;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39, :133:{22,25}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        l0_tlb_hit = last_translated_valid & io_clients_0_req_bits_tlb_req_vaddr[39:12] == {1'h0, last_translated_vpn[38:12]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:118:40, :119:38, :122:{44,79,100,125}]
  wire        l0_tlb_hit_1 = last_translated_valid_1 & io_clients_1_req_bits_tlb_req_vaddr[39:12] == {1'h0, last_translated_vpn_1[38:12]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:118:40, :119:38, :122:{44,79,100,125}]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
      last_translated_valid <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:118:40]
      last_translated_vpn <= 39'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:119:38]
      last_translated_ppn <= 32'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:120:38]
      last_translated_valid_1 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:118:40]
      last_translated_vpn_1 <= 39'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:119:38]
      last_translated_ppn_1 <= 32'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:120:38]
    end
    else begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
      last_translated_valid <= ~_GEN_0 & (_GEN | last_translated_valid);	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:25:49, :118:40, :133:{22,44}, :134:29, :139:31, :140:29]
      if (_GEN) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:133:22]
        last_translated_vpn <= tlbArbOpt_io_in_0_bits_REG_tlb_req_vaddr[38:0];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:119:38, :131:22, :135:27]
        last_translated_ppn <= _tlbs_0_io_resp_paddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39, :120:38]
      end
      last_translated_valid_1 <= ~_GEN_0 & (_GEN_1 | last_translated_valid_1);	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:25:49, :118:40, :133:{22,44}, :134:29, :139:31, :140:29]
      if (_GEN_1) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:133:22]
        last_translated_vpn_1 <= tlbArbOpt_io_in_1_bits_REG_tlb_req_vaddr[38:0];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:119:38, :131:22, :135:27]
        last_translated_ppn_1 <= _tlbs_0_io_resp_paddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39, :120:38]
      end
    end
    tlbArbOpt_io_in_0_valid_REG <= io_clients_0_req_valid & ~l0_tlb_hit;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:122:44, :130:{27,45,48}]
    tlbArbOpt_io_in_0_bits_REG_tlb_req_vaddr <= io_clients_0_req_bits_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    tlbArbOpt_io_in_0_bits_REG_tlb_req_passthrough <= io_clients_0_req_bits_tlb_req_passthrough;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    tlbArbOpt_io_in_0_bits_REG_status_debug <= io_clients_0_req_bits_status_debug;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    tlbArbOpt_io_in_0_bits_REG_status_mxr <= io_clients_0_req_bits_status_mxr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    io_clients_0_resp_paddr_REG <= {last_translated_ppn[31:12], io_clients_0_req_bits_tlb_req_vaddr[11:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:120:38, :123:{27,48,91}, :147:35]
    io_clients_0_resp_miss_REG <= l0_tlb_hit;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:122:44, :148:35]
    tlbArbOpt_io_in_1_valid_REG <= io_clients_1_req_valid & ~l0_tlb_hit_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:122:44, :130:{27,45,48}]
    tlbArbOpt_io_in_1_bits_REG_tlb_req_vaddr <= io_clients_1_req_bits_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    tlbArbOpt_io_in_1_bits_REG_status_debug <= io_clients_1_req_bits_status_debug;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    tlbArbOpt_io_in_1_bits_REG_status_mxr <= io_clients_1_req_bits_status_mxr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    io_clients_1_resp_paddr_REG <= {last_translated_ppn_1[31:12], io_clients_1_req_bits_tlb_req_vaddr[11:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:120:38, :123:{27,48,91}, :147:35]
    io_clients_1_resp_miss_REG <= l0_tlb_hit_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:122:44, :148:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:16];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
        for (logic [4:0] i = 5'h0; i < 5'h11; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
        last_translated_valid = _RANDOM[5'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :118:40]
        last_translated_vpn = {_RANDOM[5'h0][31:1], _RANDOM[5'h1][7:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :118:40, :119:38]
        last_translated_ppn = {_RANDOM[5'h1][31:8], _RANDOM[5'h2][7:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :119:38, :120:38]
        tlbArbOpt_io_in_0_valid_REG = _RANDOM[5'h2][8];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :120:38, :130:27]
        tlbArbOpt_io_in_0_bits_REG_tlb_req_vaddr = {_RANDOM[5'h2][31:9], _RANDOM[5'h3][16:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :120:38, :131:22]
        tlbArbOpt_io_in_0_bits_REG_tlb_req_passthrough = _RANDOM[5'h3][17];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :131:22]
        tlbArbOpt_io_in_0_bits_REG_status_debug = _RANDOM[5'h3][28];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :131:22]
        tlbArbOpt_io_in_0_bits_REG_status_mxr = _RANDOM[5'h6][17];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :131:22]
        io_clients_0_resp_paddr_REG = {_RANDOM[5'h7][31:5], _RANDOM[5'h8][4:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :147:35]
        io_clients_0_resp_miss_REG = _RANDOM[5'h8][5];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :147:35, :148:35]
        last_translated_valid_1 = _RANDOM[5'h8][6];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :118:40, :147:35]
        last_translated_vpn_1 = {_RANDOM[5'h8][31:7], _RANDOM[5'h9][13:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :119:38, :147:35]
        last_translated_ppn_1 = {_RANDOM[5'h9][31:14], _RANDOM[5'hA][13:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :119:38, :120:38]
        tlbArbOpt_io_in_1_valid_REG = _RANDOM[5'hA][14];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :120:38, :130:27]
        tlbArbOpt_io_in_1_bits_REG_tlb_req_vaddr = {_RANDOM[5'hA][31:15], _RANDOM[5'hB][22:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :120:38, :131:22]
        tlbArbOpt_io_in_1_bits_REG_status_debug = _RANDOM[5'hC][2];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :131:22]
        tlbArbOpt_io_in_1_bits_REG_status_mxr = _RANDOM[5'hE][23];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :131:22]
        io_clients_1_resp_paddr_REG = {_RANDOM[5'hF][31:11], _RANDOM[5'h10][10:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :147:35]
        io_clients_1_resp_miss_REG = _RANDOM[5'h10][11];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :147:35, :148:35]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DecoupledTLB tlbs_0 (	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39]
    .clock                           (clock),
    .reset                           (reset),
    .io_req_valid                    (_tlbArbOpt_io_out_valid),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
    .io_req_bits_tlb_req_vaddr       (_tlbArbOpt_io_out_bits_tlb_req_vaddr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
    .io_req_bits_tlb_req_passthrough (_tlbArbOpt_io_out_bits_tlb_req_passthrough),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
    .io_req_bits_tlb_req_cmd         (_tlbArbOpt_io_out_bits_tlb_req_cmd),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
    .io_req_bits_status_debug        (_tlbArbOpt_io_out_bits_status_debug),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
    .io_req_bits_status_mxr          (_tlbArbOpt_io_out_bits_status_mxr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
    .io_resp_miss                    (_tlbs_0_io_resp_miss),
    .io_resp_paddr                   (_tlbs_0_io_resp_paddr),
    .io_ptw_req_ready                (io_ptw_0_req_ready),
    .io_ptw_req_valid                (io_ptw_0_req_valid),
    .io_ptw_req_bits_bits_addr       (io_ptw_0_req_bits_bits_addr),
    .io_ptw_req_bits_bits_need_gpa   (io_ptw_0_req_bits_bits_need_gpa),
    .io_ptw_resp_valid               (io_ptw_0_resp_valid),
    .io_ptw_resp_bits_ae_ptw         (io_ptw_0_resp_bits_ae_ptw),
    .io_ptw_resp_bits_ae_final       (io_ptw_0_resp_bits_ae_final),
    .io_ptw_resp_bits_pf             (io_ptw_0_resp_bits_pf),
    .io_ptw_resp_bits_gf             (io_ptw_0_resp_bits_gf),
    .io_ptw_resp_bits_hr             (io_ptw_0_resp_bits_hr),
    .io_ptw_resp_bits_hw             (io_ptw_0_resp_bits_hw),
    .io_ptw_resp_bits_hx             (io_ptw_0_resp_bits_hx),
    .io_ptw_resp_bits_pte_ppn        (io_ptw_0_resp_bits_pte_ppn),
    .io_ptw_resp_bits_pte_d          (io_ptw_0_resp_bits_pte_d),
    .io_ptw_resp_bits_pte_a          (io_ptw_0_resp_bits_pte_a),
    .io_ptw_resp_bits_pte_g          (io_ptw_0_resp_bits_pte_g),
    .io_ptw_resp_bits_pte_u          (io_ptw_0_resp_bits_pte_u),
    .io_ptw_resp_bits_pte_x          (io_ptw_0_resp_bits_pte_x),
    .io_ptw_resp_bits_pte_w          (io_ptw_0_resp_bits_pte_w),
    .io_ptw_resp_bits_pte_r          (io_ptw_0_resp_bits_pte_r),
    .io_ptw_resp_bits_pte_v          (io_ptw_0_resp_bits_pte_v),
    .io_ptw_resp_bits_level          (io_ptw_0_resp_bits_level),
    .io_ptw_resp_bits_homogeneous    (io_ptw_0_resp_bits_homogeneous),
    .io_ptw_ptbr_mode                (io_ptw_0_ptbr_mode),
    .io_ptw_pmp_0_cfg_l              (io_ptw_0_pmp_0_cfg_l),
    .io_ptw_pmp_0_cfg_a              (io_ptw_0_pmp_0_cfg_a),
    .io_ptw_pmp_0_cfg_x              (io_ptw_0_pmp_0_cfg_x),
    .io_ptw_pmp_0_cfg_w              (io_ptw_0_pmp_0_cfg_w),
    .io_ptw_pmp_0_cfg_r              (io_ptw_0_pmp_0_cfg_r),
    .io_ptw_pmp_0_addr               (io_ptw_0_pmp_0_addr),
    .io_ptw_pmp_0_mask               (io_ptw_0_pmp_0_mask),
    .io_ptw_pmp_1_cfg_l              (io_ptw_0_pmp_1_cfg_l),
    .io_ptw_pmp_1_cfg_a              (io_ptw_0_pmp_1_cfg_a),
    .io_ptw_pmp_1_cfg_x              (io_ptw_0_pmp_1_cfg_x),
    .io_ptw_pmp_1_cfg_w              (io_ptw_0_pmp_1_cfg_w),
    .io_ptw_pmp_1_cfg_r              (io_ptw_0_pmp_1_cfg_r),
    .io_ptw_pmp_1_addr               (io_ptw_0_pmp_1_addr),
    .io_ptw_pmp_1_mask               (io_ptw_0_pmp_1_mask),
    .io_ptw_pmp_2_cfg_l              (io_ptw_0_pmp_2_cfg_l),
    .io_ptw_pmp_2_cfg_a              (io_ptw_0_pmp_2_cfg_a),
    .io_ptw_pmp_2_cfg_x              (io_ptw_0_pmp_2_cfg_x),
    .io_ptw_pmp_2_cfg_w              (io_ptw_0_pmp_2_cfg_w),
    .io_ptw_pmp_2_cfg_r              (io_ptw_0_pmp_2_cfg_r),
    .io_ptw_pmp_2_addr               (io_ptw_0_pmp_2_addr),
    .io_ptw_pmp_2_mask               (io_ptw_0_pmp_2_mask),
    .io_ptw_pmp_3_cfg_l              (io_ptw_0_pmp_3_cfg_l),
    .io_ptw_pmp_3_cfg_a              (io_ptw_0_pmp_3_cfg_a),
    .io_ptw_pmp_3_cfg_x              (io_ptw_0_pmp_3_cfg_x),
    .io_ptw_pmp_3_cfg_w              (io_ptw_0_pmp_3_cfg_w),
    .io_ptw_pmp_3_cfg_r              (io_ptw_0_pmp_3_cfg_r),
    .io_ptw_pmp_3_addr               (io_ptw_0_pmp_3_addr),
    .io_ptw_pmp_3_mask               (io_ptw_0_pmp_3_mask),
    .io_ptw_pmp_4_cfg_l              (io_ptw_0_pmp_4_cfg_l),
    .io_ptw_pmp_4_cfg_a              (io_ptw_0_pmp_4_cfg_a),
    .io_ptw_pmp_4_cfg_x              (io_ptw_0_pmp_4_cfg_x),
    .io_ptw_pmp_4_cfg_w              (io_ptw_0_pmp_4_cfg_w),
    .io_ptw_pmp_4_cfg_r              (io_ptw_0_pmp_4_cfg_r),
    .io_ptw_pmp_4_addr               (io_ptw_0_pmp_4_addr),
    .io_ptw_pmp_4_mask               (io_ptw_0_pmp_4_mask),
    .io_ptw_pmp_5_cfg_l              (io_ptw_0_pmp_5_cfg_l),
    .io_ptw_pmp_5_cfg_a              (io_ptw_0_pmp_5_cfg_a),
    .io_ptw_pmp_5_cfg_x              (io_ptw_0_pmp_5_cfg_x),
    .io_ptw_pmp_5_cfg_w              (io_ptw_0_pmp_5_cfg_w),
    .io_ptw_pmp_5_cfg_r              (io_ptw_0_pmp_5_cfg_r),
    .io_ptw_pmp_5_addr               (io_ptw_0_pmp_5_addr),
    .io_ptw_pmp_5_mask               (io_ptw_0_pmp_5_mask),
    .io_ptw_pmp_6_cfg_l              (io_ptw_0_pmp_6_cfg_l),
    .io_ptw_pmp_6_cfg_a              (io_ptw_0_pmp_6_cfg_a),
    .io_ptw_pmp_6_cfg_x              (io_ptw_0_pmp_6_cfg_x),
    .io_ptw_pmp_6_cfg_w              (io_ptw_0_pmp_6_cfg_w),
    .io_ptw_pmp_6_cfg_r              (io_ptw_0_pmp_6_cfg_r),
    .io_ptw_pmp_6_addr               (io_ptw_0_pmp_6_addr),
    .io_ptw_pmp_6_mask               (io_ptw_0_pmp_6_mask),
    .io_ptw_pmp_7_cfg_l              (io_ptw_0_pmp_7_cfg_l),
    .io_ptw_pmp_7_cfg_a              (io_ptw_0_pmp_7_cfg_a),
    .io_ptw_pmp_7_cfg_x              (io_ptw_0_pmp_7_cfg_x),
    .io_ptw_pmp_7_cfg_w              (io_ptw_0_pmp_7_cfg_w),
    .io_ptw_pmp_7_cfg_r              (io_ptw_0_pmp_7_cfg_r),
    .io_ptw_pmp_7_addr               (io_ptw_0_pmp_7_addr),
    .io_ptw_pmp_7_mask               (io_ptw_0_pmp_7_mask),
    .io_exp_interrupt                (io_exp_0_interrupt),
    .io_exp_flush_retry              (io_exp_0_flush_retry),
    .io_exp_flush_skip               (io_exp_0_flush_skip),
    .io_counter_event_signal_15      (io_counter_event_signal_15),
    .io_counter_event_signal_16      (io_counter_event_signal_16),
    .io_counter_event_signal_17      (io_counter_event_signal_17)
  );	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:102:39]
  RRArbiter_4 tlbArbOpt (	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
    .clock                            (clock),
    .io_in_0_ready                    (_tlbArbOpt_io_in_0_ready),
    .io_in_0_valid                    (tlbArbOpt_io_in_0_valid_REG),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:130:27]
    .io_in_0_bits_tlb_req_vaddr       (tlbArbOpt_io_in_0_bits_REG_tlb_req_vaddr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    .io_in_0_bits_tlb_req_passthrough (tlbArbOpt_io_in_0_bits_REG_tlb_req_passthrough),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    .io_in_0_bits_status_debug        (tlbArbOpt_io_in_0_bits_REG_status_debug),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    .io_in_0_bits_status_mxr          (tlbArbOpt_io_in_0_bits_REG_status_mxr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    .io_in_1_ready                    (_tlbArbOpt_io_in_1_ready),
    .io_in_1_valid                    (tlbArbOpt_io_in_1_valid_REG),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:130:27]
    .io_in_1_bits_tlb_req_vaddr       (tlbArbOpt_io_in_1_bits_REG_tlb_req_vaddr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    .io_in_1_bits_status_debug        (tlbArbOpt_io_in_1_bits_REG_status_debug),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    .io_in_1_bits_status_mxr          (tlbArbOpt_io_in_1_bits_REG_status_mxr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:131:22]
    .io_out_valid                     (_tlbArbOpt_io_out_valid),
    .io_out_bits_tlb_req_vaddr        (_tlbArbOpt_io_out_bits_tlb_req_vaddr),
    .io_out_bits_tlb_req_passthrough  (_tlbArbOpt_io_out_bits_tlb_req_passthrough),
    .io_out_bits_tlb_req_cmd          (_tlbArbOpt_io_out_bits_tlb_req_cmd),
    .io_out_bits_status_debug         (_tlbArbOpt_io_out_bits_status_debug),
    .io_out_bits_status_mxr           (_tlbArbOpt_io_out_bits_status_mxr)
  );	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:107:50]
  assign io_clients_0_resp_miss = tlbReqFire ? _tlbs_0_io_resp_miss : ~io_clients_0_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :102:39, :143:23, :144:19, :148:{24,27,35}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_clients_0_resp_paddr = tlbReqFire ? _tlbs_0_io_resp_paddr : io_clients_0_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :102:39, :143:23, :144:19, :147:{25,35}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_clients_1_resp_miss = tlbReqFire_1 ? _tlbs_0_io_resp_miss : ~io_clients_1_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :102:39, :143:23, :144:19, :148:{24,27,35}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_clients_1_resp_paddr = tlbReqFire_1 ? _tlbs_0_io_resp_paddr : io_clients_1_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:89:7, :102:39, :143:23, :144:19, :147:{25,35}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
endmodule

