// Generated by CIRCT firtool-1.75.0
module GenericSerializer_TLBeatw10_f32(	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:8:7]
  input         io_in_bits_head,	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:10:14]
  output [31:0] io_out_bits_flit	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:10:14]
);

  assign io_out_bits_flit = {30'h0, io_in_bits_head, 1'h1};	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:8:7, :10:14, :24:26]
endmodule

