// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module HellaCacheArbiter(	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  output        io_requestor_0_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_requestor_0_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [39:0] io_requestor_0_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_requestor_0_s1_kill,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_0_s2_nack,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_0_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [63:0] io_requestor_0_resp_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_0_s2_xcpt_ae_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_requestor_1_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [63:0] io_requestor_1_s1_data_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [7:0]  io_requestor_1_s1_data_mask,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_s2_nack,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [7:0]  io_requestor_1_resp_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_s2_xcpt_ma_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_s2_xcpt_ma_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_s2_xcpt_pf_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_s2_xcpt_pf_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_s2_xcpt_ae_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_1_s2_xcpt_ae_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_requestor_2_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [39:0] io_requestor_2_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [7:0]  io_requestor_2_req_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [4:0]  io_requestor_2_req_bits_cmd,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [1:0]  io_requestor_2_req_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_requestor_2_req_bits_signed,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [1:0]  io_requestor_2_req_bits_dprv,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_requestor_2_req_bits_dv,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_requestor_2_s1_kill,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [63:0] io_requestor_2_s1_data_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_s2_nack,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [7:0]  io_requestor_2_resp_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [1:0]  io_requestor_2_resp_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [63:0] io_requestor_2_resp_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_resp_bits_replay,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_resp_bits_has_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [63:0] io_requestor_2_resp_bits_data_word_bypass,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_replay_next,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_s2_xcpt_ma_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_s2_xcpt_ma_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_s2_xcpt_pf_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_s2_xcpt_pf_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_s2_xcpt_ae_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_s2_xcpt_ae_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_ordered,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_perf_release,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_requestor_2_perf_grant,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_mem_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [39:0] io_mem_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [7:0]  io_mem_req_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [4:0]  io_mem_req_bits_cmd,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [1:0]  io_mem_req_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_mem_req_bits_signed,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [1:0]  io_mem_req_bits_dprv,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_mem_req_bits_dv,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_mem_req_bits_phys,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output        io_mem_s1_kill,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [63:0] io_mem_s1_data_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  output [7:0]  io_mem_s1_data_mask,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_s2_nack,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [7:0]  io_mem_resp_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [1:0]  io_mem_resp_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [63:0] io_mem_resp_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_resp_bits_replay,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_resp_bits_has_data,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input  [63:0] io_mem_resp_bits_data_word_bypass,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_replay_next,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_s2_xcpt_ma_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_s2_xcpt_ma_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_s2_xcpt_pf_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_s2_xcpt_pf_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_s2_xcpt_ae_ld,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_s2_xcpt_ae_st,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_ordered,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_perf_release,	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
  input         io_mem_perf_grant	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:12:14]
);

  reg  [1:0] s1_id;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:20:20]
  reg  [1:0] s2_id;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:21:24]
  wire       io_requestor_1_req_ready_0 = io_mem_req_ready & ~io_requestor_0_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:28:{64,67}]
  wire       _GEN = s1_id == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:20:20, :51:21]
  wire       _GEN_0 = s1_id == 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:20:20, :51:21]
  wire [7:0] io_requestor_2_resp_bits_tag_0 = {2'h0, io_mem_resp_bits_tag[7:2]};	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:74:{21,45}]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
    if (io_requestor_0_req_valid)	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
      s1_id <= 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:20:20]
    else	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
      s1_id <= io_requestor_1_req_valid ? 2'h1 : 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:20:20, :35:15, :50:26, :51:21]
    s2_id <= s1_id;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:20:20, :21:24]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
    initial begin	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
        s1_id = _RANDOM[/*Zero width*/ 1'b0][1:0];	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :20:20]
        s2_id = _RANDOM[/*Zero width*/ 1'b0][3:2];	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :20:20, :21:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_requestor_0_req_ready = io_mem_req_ready;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_0_s2_nack = io_mem_s2_nack & s2_id == 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :21:24, :52:21, :68:49]
  assign io_requestor_0_resp_valid = io_mem_resp_valid & io_mem_resp_bits_tag[1:0] == 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :60:{41,57}, :61:39]
  assign io_requestor_0_resp_bits_data = io_mem_resp_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_0_s2_xcpt_ae_ld = io_mem_s2_xcpt_ae_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_1_req_ready = io_requestor_1_req_ready_0;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :28:64]
  assign io_requestor_1_s2_nack = io_mem_s2_nack & s2_id == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :21:24, :51:21, :52:21, :68:49]
  assign io_requestor_1_resp_valid = io_mem_resp_valid & io_mem_resp_bits_tag[1:0] == 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :51:21, :60:{41,57}, :61:39]
  assign io_requestor_1_resp_bits_tag = io_requestor_2_resp_bits_tag_0;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :74:21]
  assign io_requestor_1_s2_xcpt_ma_ld = io_mem_s2_xcpt_ma_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_1_s2_xcpt_ma_st = io_mem_s2_xcpt_ma_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_1_s2_xcpt_pf_ld = io_mem_s2_xcpt_pf_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_1_s2_xcpt_pf_st = io_mem_s2_xcpt_pf_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_1_s2_xcpt_ae_ld = io_mem_s2_xcpt_ae_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_1_s2_xcpt_ae_st = io_mem_s2_xcpt_ae_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_req_ready = io_requestor_1_req_ready_0 & ~io_requestor_1_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :28:{64,67}]
  assign io_requestor_2_s2_nack = io_mem_s2_nack & s2_id == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :21:24, :68:{49,58}]
  assign io_requestor_2_resp_valid = io_mem_resp_valid & io_mem_resp_bits_tag[1:0] == 2'h2;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :60:{41,57}, :61:39]
  assign io_requestor_2_resp_bits_tag = io_requestor_2_resp_bits_tag_0;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :74:21]
  assign io_requestor_2_resp_bits_size = io_mem_resp_bits_size;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_resp_bits_data = io_mem_resp_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_resp_bits_replay = io_mem_resp_bits_replay;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_resp_bits_has_data = io_mem_resp_bits_has_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_resp_bits_data_word_bypass = io_mem_resp_bits_data_word_bypass;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_replay_next = io_mem_replay_next;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_s2_xcpt_ma_ld = io_mem_s2_xcpt_ma_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_s2_xcpt_ma_st = io_mem_s2_xcpt_ma_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_s2_xcpt_pf_ld = io_mem_s2_xcpt_pf_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_s2_xcpt_pf_st = io_mem_s2_xcpt_pf_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_s2_xcpt_ae_ld = io_mem_s2_xcpt_ae_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_s2_xcpt_ae_st = io_mem_s2_xcpt_ae_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_ordered = io_mem_ordered;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_perf_release = io_mem_perf_release;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_requestor_2_perf_grant = io_mem_perf_grant;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_mem_req_valid = io_requestor_0_req_valid | io_requestor_1_req_valid | io_requestor_2_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :25:63]
  assign io_mem_req_bits_addr = io_requestor_0_req_valid ? io_requestor_0_req_bits_addr : io_requestor_1_req_valid ? 40'h0 : io_requestor_2_req_bits_addr;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :12:14, :33:25, :50:26]
  assign io_mem_req_bits_tag = io_requestor_0_req_valid ? 8'h0 : io_requestor_1_req_valid ? 8'h1 : {io_requestor_2_req_bits_tag[5:0], 2'h2};	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :12:14, :34:29, :50:26]
  assign io_mem_req_bits_cmd = io_requestor_0_req_valid | io_requestor_1_req_valid ? 5'h0 : io_requestor_2_req_bits_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :33:25, :50:26]
  assign io_mem_req_bits_size = io_requestor_0_req_valid ? 2'h3 : io_requestor_1_req_valid ? 2'h0 : io_requestor_2_req_bits_size;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :12:14, :33:25, :50:26]
  assign io_mem_req_bits_signed = ~io_requestor_0_req_valid & ~io_requestor_1_req_valid & io_requestor_2_req_bits_signed;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :33:25, :50:26]
  assign io_mem_req_bits_dprv = io_requestor_0_req_valid ? 2'h1 : io_requestor_1_req_valid ? 2'h0 : io_requestor_2_req_bits_dprv;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :33:25, :50:26, :51:21]
  assign io_mem_req_bits_dv = ~io_requestor_0_req_valid & ~io_requestor_1_req_valid & io_requestor_2_req_bits_dv;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :33:25, :50:26]
  assign io_mem_req_bits_phys = io_requestor_0_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7]
  assign io_mem_s1_kill = _GEN_0 ? io_requestor_0_s1_kill : ~_GEN & io_requestor_2_s1_kill;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :38:24, :51:{21,30}]
  assign io_mem_s1_data_data = _GEN_0 ? 64'h0 : _GEN ? io_requestor_1_s1_data_data : io_requestor_2_s1_data_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :12:14, :39:24, :51:{21,30}]
  assign io_mem_s1_data_mask = _GEN_0 | ~_GEN ? 8'h0 : io_requestor_1_s1_data_mask;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCacheArbiter.scala:10:7, :12:14, :34:29, :38:24, :39:24, :51:{21,30}]
endmodule

