// Generated by CIRCT firtool-1.75.0
module mem(	// @[generators/gemmini/src/main/scala/gemmini/Scratchpad.scala:163:26]
  input  [11:0]  RW0_addr,
  input          RW0_en,
  input          RW0_clk,
  input          RW0_wmode,
  input  [127:0] RW0_wdata,
  output [127:0] RW0_rdata,
  input  [15:0]  RW0_wmask
);

  mem_ext mem_ext (	// @[generators/gemmini/src/main/scala/gemmini/Scratchpad.scala:163:26]
    .RW0_addr  (RW0_addr),
    .RW0_en    (RW0_en),
    .RW0_clk   (RW0_clk),
    .RW0_wmode (RW0_wmode),
    .RW0_wdata (RW0_wdata),
    .RW0_rdata (RW0_rdata),
    .RW0_wmask (RW0_wmask)
  );	// @[generators/gemmini/src/main/scala/gemmini/Scratchpad.scala:163:26]
endmodule

