// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLBFromBeat_SerialRAM_a64d64s8k8z8c(	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
  input  clock,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
  input  reset,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
  output io_beat_ready,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:75:14]
  input  io_beat_valid,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:75:14]
  input  io_beat_bits_head,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:75:14]
  input  io_beat_bits_tail	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:75:14]
);

  reg  is_const;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:88:25]
  wire io_beat_ready_0 = is_const & ~io_beat_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:88:25, :91:{30,33}]
  wire _GEN = io_beat_ready_0 & io_beat_valid;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:91:30, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
    if (reset)	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
      is_const <= 1'h1;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:88:25, :120:7]
    else	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
      is_const <= _GEN & io_beat_bits_tail | ~(_GEN & io_beat_bits_head) & is_const;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:88:25, :104:{22,44,55}, :105:{22,44,55}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
    initial begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
        `INIT_RANDOM_PROLOG_	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
        is_const = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:88:25, :120:7]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:120:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_beat_ready = io_beat_ready_0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:91:30, :120:7]
endmodule

