// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLMonitor_28(	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        clock,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        reset,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        io_in_a_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_a_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_param,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [7:0]  io_in_a_bits_source,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [11:0] io_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [7:0]  io_in_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_d_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_d_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [7:0]  io_in_d_bits_source	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
);

  wire [31:0]   _plusarg_reader_1_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire [31:0]   _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire [12:0]   _GEN = {10'h0, io_in_a_bits_size};	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire          _a_first_T_1 = io_in_a_ready & io_in_a_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [2:0]    a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg  [2:0]    opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
  reg  [2:0]    param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
  reg  [2:0]    size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:389:22]
  reg  [7:0]    source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:390:22]
  reg  [11:0]   address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:391:22]
  reg  [2:0]    d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg  [2:0]    opcode_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
  reg  [2:0]    size_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
  reg  [7:0]    source_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:541:22]
  reg  [128:0]  inflight;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27]
  reg  [515:0]  inflight_opcodes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35]
  reg  [515:0]  inflight_sizes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33]
  reg  [2:0]    a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire          a_first_1 = a_first_counter_1 == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  reg  [2:0]    d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire          d_first_1 = d_first_counter_1 == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  wire          _GEN_0 = _a_first_T_1 & a_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:655:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire          d_release_ack = io_in_d_bits_opcode == 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:673:46]
  wire          _GEN_1 = io_in_d_bits_opcode != 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:673:46, :674:74]
  reg  [31:0]   watchdog;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:709:27]
  reg  [128:0]  inflight_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:726:35]
  reg  [515:0]  inflight_sizes_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:728:35]
  reg  [2:0]    d_first_counter_2;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire          d_first_2 = d_first_counter_2 == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  reg  [31:0]   watchdog_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:818:27]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
    wire [7:0][2:0] _GEN_2 = '{3'h4, 3'h5, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};
    wire [7:0][2:0] _GEN_3 = '{3'h4, 3'h4, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};
    wire            _source_ok_T = io_in_a_bits_source == 8'h30;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            _source_ok_T_37 = io_in_a_bits_source == 8'h40;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            _source_ok_T_38 = io_in_a_bits_source == 8'h41;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            _source_ok_T_39 = io_in_a_bits_source == 8'h42;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            _source_ok_T_40 = io_in_a_bits_source == 8'h80;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire            source_ok = _source_ok_T | io_in_a_bits_source[7:2] == 6'h8 | io_in_a_bits_source[7:2] == 6'h9 | io_in_a_bits_source[7:2] == 6'hA | io_in_a_bits_source[7:2] == 6'hB | io_in_a_bits_source[7:4] == 4'h1 | ~(|(io_in_a_bits_source[7:4])) | _source_ok_T_37 | _source_ok_T_38 | _source_ok_T_39 | _source_ok_T_40;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
    wire [12:0]     _is_aligned_mask_T = 13'h3F << _GEN;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
    wire [5:0]      _GEN_4 = io_in_a_bits_address[5:0] & ~(_is_aligned_mask_T[5:0]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:16, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
    wire            mask_sub_sub_sub_0_1 = io_in_a_bits_size > 3'h2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
    wire            mask_sub_sub_size = io_in_a_bits_size[1:0] == 2'h2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49]
    wire            mask_sub_sub_0_1 = mask_sub_sub_sub_0_1 | mask_sub_sub_size & ~(io_in_a_bits_address[2]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
    wire            mask_sub_sub_1_1 = mask_sub_sub_sub_0_1 | mask_sub_sub_size & io_in_a_bits_address[2];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
    wire            mask_sub_size = io_in_a_bits_size[1:0] == 2'h1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, src/main/scala/chisel3/util/OneHot.scala:64:49]
    wire            mask_sub_0_2 = ~(io_in_a_bits_address[2]) & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_sub_0_1 = mask_sub_sub_0_1 | mask_sub_size & mask_sub_0_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_sub_1_2 = ~(io_in_a_bits_address[2]) & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_sub_1_1 = mask_sub_sub_0_1 | mask_sub_size & mask_sub_1_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_sub_2_2 = io_in_a_bits_address[2] & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_sub_2_1 = mask_sub_sub_1_1 | mask_sub_size & mask_sub_2_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_sub_3_2 = io_in_a_bits_address[2] & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
    wire            mask_sub_3_1 = mask_sub_sub_1_1 | mask_sub_size & mask_sub_3_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire [7:0]      mask = {mask_sub_3_1 | mask_sub_3_2 & io_in_a_bits_address[0], mask_sub_3_1 | mask_sub_3_2 & ~(io_in_a_bits_address[0]), mask_sub_2_1 | mask_sub_2_2 & io_in_a_bits_address[0], mask_sub_2_1 | mask_sub_2_2 & ~(io_in_a_bits_address[0]), mask_sub_1_1 | mask_sub_1_2 & io_in_a_bits_address[0], mask_sub_1_1 | mask_sub_1_2 & ~(io_in_a_bits_address[0]), mask_sub_0_1 | mask_sub_0_2 & io_in_a_bits_address[0], mask_sub_0_1 | mask_sub_0_2 & ~(io_in_a_bits_address[0])};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10]
    wire            _GEN_5 = io_in_a_valid & io_in_a_bits_opcode == 3'h6 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:{25,54}]
    wire            _GEN_6 = _source_ok_T_37 & io_in_a_bits_size == 3'h6;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :91:44, src/main/scala/chisel3/util/Mux.scala:30:73]
    wire            _GEN_7 = io_in_a_bits_size < 3'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
    wire            _GEN_8 = io_in_a_bits_param > 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
    wire            _GEN_9 = io_in_a_bits_mask != 8'hFF;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:91:31]
    wire            _GEN_10 = io_in_a_valid & (&io_in_a_bits_opcode) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:{25,53}]
    wire            _GEN_11 = _source_ok_T | io_in_a_bits_source[7:2] == 6'h8 | io_in_a_bits_source[7:2] == 6'h9 | io_in_a_bits_source[7:2] == 6'hA | io_in_a_bits_source[7:2] == 6'hB | io_in_a_bits_source[7:4] == 4'h1 | ~(|(io_in_a_bits_source[7:4])) | _source_ok_T_37 | _source_ok_T_38 | _source_ok_T_39 | _source_ok_T_40;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1175:43]
    wire            _GEN_12 = io_in_a_valid & io_in_a_bits_opcode == 3'h4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:{25,45}]
    wire            _GEN_13 = io_in_a_bits_size != 3'h7;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:92:38, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
    wire            _GEN_14 = io_in_a_bits_mask != mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
    wire            _GEN_15 = _GEN_11 & _GEN_13;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:92:38, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :118:71, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1175:43]
    wire            _GEN_16 = io_in_a_valid & io_in_a_bits_opcode == 3'h0 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:{25,53}]
    wire            _GEN_17 = io_in_a_valid & io_in_a_bits_opcode == 3'h1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:{25,56}]
    wire            _GEN_18 = io_in_a_valid & io_in_a_bits_opcode == 3'h2 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:{25,56}]
    wire            _GEN_19 = io_in_a_valid & io_in_a_bits_opcode == 3'h3 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:{25,53}]
    wire            _GEN_20 = io_in_a_valid & io_in_a_bits_opcode == 3'h5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:{25,46}]
    wire            source_ok_1 = io_in_d_bits_source == 8'h30 | io_in_d_bits_source[7:2] == 6'h8 | io_in_d_bits_source[7:2] == 6'h9 | io_in_d_bits_source[7:2] == 6'hA | io_in_d_bits_source[7:2] == 6'hB | io_in_d_bits_source[7:4] == 4'h1 | io_in_d_bits_source[7:4] == 4'h0 | io_in_d_bits_source == 8'h40 | io_in_d_bits_source == 8'h41 | io_in_d_bits_source == 8'h42 | io_in_d_bits_source == 8'h80;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
    wire            _GEN_21 = io_in_d_valid & io_in_d_bits_opcode == 3'h6 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :313:{25,52}]
    wire            _GEN_22 = io_in_d_bits_size < 3'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :315:27]
    wire            _GEN_23 = io_in_d_valid & io_in_d_bits_opcode == 3'h4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :321:{25,47}]
    wire            _GEN_24 = io_in_d_valid & io_in_d_bits_opcode == 3'h5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :331:{25,51}]
    wire            _GEN_25 = io_in_a_valid & (|a_first_counter) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :392:19]
    wire            _GEN_26 = io_in_d_valid & (|d_first_counter) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :544:19]
    wire [515:0]    _GEN_27 = {506'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:637:44]
    wire [515:0]    _a_opcode_lookup_T_1 = inflight_opcodes >> _GEN_27;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35, :637:44]
    wire            _GEN_28 = io_in_d_valid & d_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:674:26]
    wire            _GEN_29 = _GEN_28 & _GEN_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:673:46, :674:{26,74}, :683:71]
    wire            same_cycle_resp = io_in_a_valid & a_first_1 & io_in_a_bits_source == io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:651:26, :684:{88,113}]
    wire [128:0]    _GEN_30 = {121'h0, io_in_d_bits_source};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:661:26, :685:25]
    wire            _GEN_31 = _GEN_29 & same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :651:26, :683:71, :684:88, :687:30]
    wire            _GEN_32 = _GEN_29 & ~same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :651:26, :683:71, :684:88, :687:30]
    wire            _GEN_33 = io_in_d_valid & d_first_2 & d_release_ack & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :673:46, :784:26, :794:71]
    wire [128:0]    _GEN_34 = inflight >> io_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27, :661:26]
    wire [128:0]    _GEN_35 = inflight >> _GEN_30;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27, :685:25]
    wire [515:0]    _a_size_lookup_T_1 = inflight_sizes >> _GEN_27;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33, :637:44, :641:40]
    wire [128:0]    _GEN_36 = inflight_1 >> _GEN_30;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:685:25, :726:35, :796:25]
    wire [515:0]    _c_size_lookup_T_1 = inflight_sizes_1 >> _GEN_27;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:637:44, :728:35, :750:42]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      if (_GEN_5) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & ~_GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, src/main/scala/chisel3/util/Mux.scala:30:73]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & _GEN_8) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid grow param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & _GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, :91:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock is corrupt (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & ~_GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, src/main/scala/chisel3/util/Mux.scala:30:73]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & _GEN_8) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid grow param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & ~(|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, :102:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm requests NtoB (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & _GEN_9) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :91:31, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm is corrupt (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & ~_GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1175:43]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Get type which master claims it can't emit (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & ~_GEN_13) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:92:38, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Get type which slave claims it can't support (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & _GEN_14) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, :113:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get is corrupt (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & ~_GEN_15) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53, :118:71]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries PutFull type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & _GEN_14) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & ~_GEN_15) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :118:71, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries PutPartial type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & (|(io_in_a_bits_mask & ~mask))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56, :130:{31,33,40}, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_18) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Arithmetic type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_18 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_18 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_18 & io_in_a_bits_param > 3'h4) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:141:33, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_18 & _GEN_14) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_19) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Logical type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_19 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_19 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_19 & io_in_a_bits_param[2]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:148:30, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_19 & _GEN_14) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_20) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Hint type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_20 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_20 & (|_GEN_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_20 & (|(io_in_a_bits_param[2:1]))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:161:28, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_20 & _GEN_14) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_20 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint is corrupt (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (io_in_d_valid & ~reset & (&io_in_d_bits_opcode)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:45:24, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel has invalid opcode (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_21 & ~source_ok_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :313:52, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel ReleaseAck carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_21 & _GEN_22) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :313:52, :315:27]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel ReleaseAck smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_23 & ~source_ok_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :321:47, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel Grant carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_23) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :321:47]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel Grant carries invalid sink ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_23 & _GEN_22) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :315:27, :321:47]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel Grant smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_24 & ~source_ok_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :331:51, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel GrantData carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_24) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :331:51]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel GrantData carries invalid sink ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_24 & _GEN_22) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :315:27, :331:51]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel GrantData smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (io_in_d_valid & io_in_d_bits_opcode == 3'h0 & ~reset & ~source_ok_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :341:{25,51}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel AccessAck carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (io_in_d_valid & io_in_d_bits_opcode == 3'h1 & ~reset & ~source_ok_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :349:{25,55}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel AccessAckData carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (io_in_d_valid & io_in_d_bits_opcode == 3'h2 & ~reset & ~source_ok_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :357:{25,49}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel HintAck carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_25 & io_in_a_bits_opcode != opcode) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :387:22, :392:19, :393:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_25 & io_in_a_bits_param != param) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :388:22, :392:19, :394:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel param changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_25 & io_in_a_bits_size != size) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :389:22, :392:19, :395:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_25 & io_in_a_bits_source != source) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :390:22, :392:19, :396:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_25 & io_in_a_bits_address != address) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :391:22, :392:19, :397:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel address changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_26 & io_in_d_bits_opcode != opcode_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :538:22, :544:19, :545:29]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_26 & io_in_d_bits_size != size_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :540:22, :544:19, :547:29]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_26 & io_in_d_bits_source != source_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :541:22, :544:19, :548:29]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_0 & ~reset & _GEN_34[0]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :655:25, :661:26]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel re-used a source ID (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_29 & ~reset & ~(_GEN_35[0] | same_cycle_resp)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :651:26, :683:71, :684:88, :685:{25,49}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_31 & ~(io_in_d_bits_opcode == _GEN_3[io_in_a_bits_opcode] | io_in_d_bits_opcode == _GEN_2[io_in_a_bits_opcode])) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :687:30, :688:{38,77}, :689:39]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_31 & io_in_a_bits_size != io_in_d_bits_size) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :687:30, :690:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_32 & ~(io_in_d_bits_opcode == _GEN_3[_a_opcode_lookup_T_1[3:1]] | io_in_d_bits_opcode == _GEN_2[_a_opcode_lookup_T_1[3:1]])) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :637:{44,152}, :687:30, :692:{38,72}, :693:38]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_32 & io_in_d_bits_size != _a_size_lookup_T_1[3:1]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :641:{40,144}, :687:30, :694:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_28 & a_first_1 & io_in_a_valid & io_in_a_bits_source == io_in_d_bits_source & _GEN_1 & ~reset & ~(~io_in_d_ready | io_in_a_ready)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :673:46, :674:{26,74}, :697:{36,47,65,90,116}, :698:{15,32}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: ready check\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (~reset & ~(inflight == 129'h0 | _plusarg_reader_out == 32'h0 | watchdog < _plusarg_reader_out)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :614:27, :709:27, :712:{26,30,39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_33 & ~(_GEN_36[0])) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :784:26, :794:71, :796:25]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_33 & io_in_d_bits_size != _c_size_lookup_T_1[3:1]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :750:{42,146}, :784:26, :794:71, :800:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (~reset & ~(inflight_1 == 129'h0 | _plusarg_reader_1_out == 32'h0 | watchdog_1 < _plusarg_reader_1_out)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :726:35, :818:27, :821:{26,30,39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:90:119)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [12:0]   _a_first_beats1_decode_T_3 = 13'h3F << _GEN;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [12:0]   _d_first_beats1_decode_T_6 = 13'h3F << io_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [2050:0] _GEN_37 = {2041'h0, io_in_a_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:659:54]
  wire [255:0]  _GEN_38 = {248'h0, io_in_d_bits_source};	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [2062:0] _GEN_39 = {2053'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:680:76]
  wire [255:0]  _d_clr_T = 256'h1 << _GEN_38;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [255:0]  _a_set_T = 256'h1 << io_in_a_bits_source;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [2062:0] _d_opcodes_clr_T_5 = 2063'hF << _GEN_39;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:680:76]
  wire [2050:0] _a_opcodes_set_T_1 = {2047'h0, _GEN_0 ? {io_in_a_bits_opcode, 1'h1} : 4'h0} << _GEN_37;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:646:40, :655:{25,70}, :657:{28,61}, :659:54]
  wire [2062:0] _d_sizes_clr_T_5 = 2063'hF << _GEN_39;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:680:76, :681:74]
  wire [2050:0] _a_sizes_set_T_1 = {2047'h0, _GEN_0 ? {io_in_a_bits_size, 1'h1} : 4'h0} << _GEN_37;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:648:38, :655:{25,70}, :658:{28,59}, :659:54, :660:52]
  wire [255:0]  _d_clr_T_1 = 256'h1 << _GEN_38;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [2062:0] _d_sizes_clr_T_11 = 2063'hF << _GEN_39;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:680:76, :791:74]
  wire          _d_first_T_2 = io_in_d_ready & io_in_d_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire          _GEN_40 = _d_first_T_2 & d_first_1 & _GEN_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:673:46, :674:74, :678:{25,70}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire          _GEN_41 = _d_first_T_2 & d_first_2 & d_release_ack;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:673:46, :788:{25,70}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      a_first_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      d_first_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      inflight <= 129'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27]
      inflight_opcodes <= 516'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35]
      inflight_sizes <= 516'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33]
      a_first_counter_1 <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      d_first_counter_1 <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:709:27]
      inflight_1 <= 129'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:726:35]
      inflight_sizes_1 <= 516'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:728:35]
      d_first_counter_2 <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      watchdog_1 <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:818:27]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      if (_a_first_T_1) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        a_first_counter <= (|a_first_counter) ? a_first_counter - 3'h1 : io_in_a_bits_opcode[2] ? 3'h0 : ~(_a_first_beats1_decode_T_3[5:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
        a_first_counter_1 <= a_first_1 ? (io_in_a_bits_opcode[2] ? 3'h0 : ~(_a_first_beats1_decode_T_3[5:3])) : a_first_counter_1 - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
      end
      if (_d_first_T_2) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        d_first_counter <= (|d_first_counter) ? d_first_counter - 3'h1 : io_in_d_bits_opcode[0] ? ~(_d_first_beats1_decode_T_6[5:3]) : 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
        d_first_counter_1 <= d_first_1 ? (io_in_d_bits_opcode[0] ? ~(_d_first_beats1_decode_T_6[5:3]) : 3'h0) : d_first_counter_1 - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
        d_first_counter_2 <= d_first_2 ? (io_in_d_bits_opcode[0] ? ~(_d_first_beats1_decode_T_6[5:3]) : 3'h0) : d_first_counter_2 - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
      end
      inflight <= (inflight | (_GEN_0 ? _a_set_T[128:0] : 129'h0)) & ~(_GEN_40 ? _d_clr_T[128:0] : 129'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27, :626:34, :655:{25,70}, :656:28, :664:34, :678:{25,70,89}, :679:21, :705:{27,36,38}, src/main/scala/chisel3/util/OneHot.scala:58:35]
      inflight_opcodes <= (inflight_opcodes | (_GEN_0 ? _a_opcodes_set_T_1[515:0] : 516'h0)) & ~(_GEN_40 ? _d_opcodes_clr_T_5[515:0] : 516'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35, :630:33, :655:{25,70}, :659:{28,54}, :668:33, :678:{25,70,89}, :680:{21,76}, :706:{43,60,62}]
      inflight_sizes <= (inflight_sizes | (_GEN_0 ? _a_sizes_set_T_1[515:0] : 516'h0)) & ~(_GEN_40 ? _d_sizes_clr_T_5[515:0] : 516'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33, :632:31, :655:{25,70}, :660:{28,52}, :670:31, :678:{25,70,89}, :681:{21,74}, :707:{39,54,56}]
      watchdog <= _a_first_T_1 | _d_first_T_2 ? 32'h0 : watchdog + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:709:27, :714:{14,26}, :715:{25,43,54}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      inflight_1 <= inflight_1 & ~(_GEN_41 ? _d_clr_T_1[128:0] : 129'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:726:35, :774:34, :788:{25,70,88}, :789:21, :814:{44,46}, src/main/scala/chisel3/util/OneHot.scala:58:35]
      inflight_sizes_1 <= inflight_sizes_1 & ~(_GEN_41 ? _d_sizes_clr_T_11[515:0] : 516'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:728:35, :777:34, :788:{25,70,88}, :791:{21,74}, :816:{56,58}]
      watchdog_1 <= _d_first_T_2 ? 32'h0 : watchdog_1 + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:818:27, :823:{14,26}, :824:{43,54}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
    if (_a_first_T_1 & ~(|a_first_counter)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:399:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      opcode <= io_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
      param <= io_in_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
      size <= io_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:389:22]
      source <= io_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:390:22]
      address <= io_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:391:22]
    end
    if (_d_first_T_2 & ~(|d_first_counter)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:552:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      opcode_1 <= io_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
      size_1 <= io_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
      source_1 <= io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:541:22]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:76];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        for (logic [6:0] i = 7'h0; i < 7'h4D; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        end	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        a_first_counter = _RANDOM[7'h0][2:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        opcode = _RANDOM[7'h0][5:3];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :387:22]
        param = _RANDOM[7'h0][8:6];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :388:22]
        size = _RANDOM[7'h0][11:9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :389:22]
        source = _RANDOM[7'h0][19:12];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :390:22]
        address = _RANDOM[7'h0][31:20];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :391:22]
        d_first_counter = _RANDOM[7'h1][2:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        opcode_1 = _RANDOM[7'h1][5:3];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :538:22]
        size_1 = _RANDOM[7'h1][10:8];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :540:22]
        source_1 = _RANDOM[7'h1][18:11];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :541:22]
        inflight = {_RANDOM[7'h1][31:21], _RANDOM[7'h2], _RANDOM[7'h3], _RANDOM[7'h4], _RANDOM[7'h5][21:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :614:27]
        inflight_opcodes = {_RANDOM[7'h5][31:22], _RANDOM[7'h6], _RANDOM[7'h7], _RANDOM[7'h8], _RANDOM[7'h9], _RANDOM[7'hA], _RANDOM[7'hB], _RANDOM[7'hC], _RANDOM[7'hD], _RANDOM[7'hE], _RANDOM[7'hF], _RANDOM[7'h10], _RANDOM[7'h11], _RANDOM[7'h12], _RANDOM[7'h13], _RANDOM[7'h14], _RANDOM[7'h15][25:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :614:27, :616:35]
        inflight_sizes = {_RANDOM[7'h15][31:26], _RANDOM[7'h16], _RANDOM[7'h17], _RANDOM[7'h18], _RANDOM[7'h19], _RANDOM[7'h1A], _RANDOM[7'h1B], _RANDOM[7'h1C], _RANDOM[7'h1D], _RANDOM[7'h1E], _RANDOM[7'h1F], _RANDOM[7'h20], _RANDOM[7'h21], _RANDOM[7'h22], _RANDOM[7'h23], _RANDOM[7'h24], _RANDOM[7'h25][29:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :616:35, :618:33]
        a_first_counter_1 = {_RANDOM[7'h25][31:30], _RANDOM[7'h26][0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :618:33]
        d_first_counter_1 = _RANDOM[7'h26][3:1];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        watchdog = {_RANDOM[7'h26][31:4], _RANDOM[7'h27][3:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :709:27]
        inflight_1 = {_RANDOM[7'h27][31:4], _RANDOM[7'h28], _RANDOM[7'h29], _RANDOM[7'h2A], _RANDOM[7'h2B][4:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :709:27, :726:35]
        inflight_sizes_1 = {_RANDOM[7'h3B][31:9], _RANDOM[7'h3C], _RANDOM[7'h3D], _RANDOM[7'h3E], _RANDOM[7'h3F], _RANDOM[7'h40], _RANDOM[7'h41], _RANDOM[7'h42], _RANDOM[7'h43], _RANDOM[7'h44], _RANDOM[7'h45], _RANDOM[7'h46], _RANDOM[7'h47], _RANDOM[7'h48], _RANDOM[7'h49], _RANDOM[7'h4A], _RANDOM[7'h4B][12:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :728:35]
        d_first_counter_2 = _RANDOM[7'h4B][18:16];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :728:35]
        watchdog_1 = {_RANDOM[7'h4B][31:19], _RANDOM[7'h4C][18:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :728:35, :818:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader_1 (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_1_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
endmodule

