// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLRAM_ScratchpadBank(	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [8:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [27:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [8:0]  auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_in_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire [7:0]  r_raw_data_7;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [7:0]  r_raw_data_6;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [7:0]  r_raw_data_5;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [7:0]  r_raw_data_4;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [7:0]  r_raw_data_3;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [7:0]  r_raw_data_2;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [7:0]  r_raw_data_1;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [7:0]  r_raw_data_0;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire        ren;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:306:20]
  wire        mem_MPORT_1_en;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:305:52]
  wire [63:0] _mem_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  reg         r_full;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:128:30]
  reg  [1:0]  r_size;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:131:26]
  reg  [8:0]  r_source;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:132:26]
  reg         r_read;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:133:26]
  wire [2:0]  nodeIn_d_bits_opcode = {2'h0, r_read};	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:133:26, :203:23]
  wire        nodeIn_a_ready = ~r_full | auto_in_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:128:30, :237:{41,49}]
  wire        a_fire = nodeIn_a_ready & auto_in_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:237:49, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign mem_MPORT_1_en = a_fire & auto_in_a_bits_opcode != 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:240:35, :305:{52,55}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign ren = ~mem_MPORT_1_en & a_fire;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:305:52, :306:{15,20}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg         REG;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58]
  reg  [7:0]  r_0;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  reg  [7:0]  r_1;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  reg  [7:0]  r_2;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  reg  [7:0]  r_3;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  reg  [7:0]  r_4;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  reg  [7:0]  r_5;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  reg  [7:0]  r_6;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  reg  [7:0]  r_7;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_0 = REG ? _mem_RW0_rdata[7:0] : r_0;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_1 = REG ? _mem_RW0_rdata[15:8] : r_1;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_2 = REG ? _mem_RW0_rdata[23:16] : r_2;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_3 = REG ? _mem_RW0_rdata[31:24] : r_3;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_4 = REG ? _mem_RW0_rdata[39:32] : r_4;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_5 = REG ? _mem_RW0_rdata[47:40] : r_5;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_6 = REG ? _mem_RW0_rdata[55:48] : r_6;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  assign r_raw_data_7 = REG ? _mem_RW0_rdata[63:56] : r_7;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
    if (reset)	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
      r_full <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:128:30]
    else	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
      r_full <= a_fire | ~auto_in_d_ready & r_full;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:128:30, :269:{20,29}, :270:22, :271:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (a_fire) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      r_size <= auto_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:131:26]
      r_source <= auto_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:132:26]
      r_read <= auto_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:133:26, :240:35]
    end
    REG <= ren;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:306:20, :317:58]
    if (REG) begin	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:317:58]
      r_0 <= _mem_RW0_rdata[7:0];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      r_1 <= _mem_RW0_rdata[15:8];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      r_2 <= _mem_RW0_rdata[23:16];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      r_3 <= _mem_RW0_rdata[31:24];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      r_4 <= _mem_RW0_rdata[39:32];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      r_5 <= _mem_RW0_rdata[47:40];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      r_6 <= _mem_RW0_rdata[55:48];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      r_7 <= _mem_RW0_rdata[63:56];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:11];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
        end	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
        r_full = _RANDOM[4'h5][27];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :128:30]
        r_size = _RANDOM[4'h6][3:2];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :131:26]
        r_source = _RANDOM[4'h6][12:4];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :131:26, :132:26]
        r_read = _RANDOM[4'h6][13];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :131:26, :133:26]
        REG = _RANDOM[4'h9][22];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :317:58]
        r_0 = _RANDOM[4'h9][30:23];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :317:58, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        r_1 = {_RANDOM[4'h9][31], _RANDOM[4'hA][6:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :317:58, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        r_2 = _RANDOM[4'hA][14:7];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        r_3 = _RANDOM[4'hA][22:15];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        r_4 = _RANDOM[4'hA][30:23];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        r_5 = {_RANDOM[4'hA][31], _RANDOM[4'hB][6:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        r_6 = _RANDOM[4'hB][14:7];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        r_7 = _RANDOM[4'hB][22:15];	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_60 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (nodeIn_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:237:49]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (r_full),	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:128:30]
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:203:23]
    .io_in_d_bits_size    (r_size),	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:131:26]
    .io_in_d_bits_source  (r_source)	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:132:26]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  mem_1 mem (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (auto_in_a_bits_address[15:3]),	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:316:20]
    .RW0_en    (ren | mem_MPORT_1_en),	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:305:52, :306:20, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (mem_MPORT_1_en),	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:305:52]
    .RW0_wdata (auto_in_a_bits_data),
    .RW0_rdata (_mem_RW0_rdata),
    .RW0_wmask (auto_in_a_bits_mask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign auto_in_a_ready = nodeIn_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :237:49]
  assign auto_in_d_valid = r_full;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :128:30]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :203:23]
  assign auto_in_d_bits_size = r_size;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :131:26]
  assign auto_in_d_bits_source = r_source;	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :132:26]
  assign auto_in_d_bits_data = {r_raw_data_7, r_raw_data_6, r_raw_data_5, r_raw_data_4, r_raw_data_3, r_raw_data_2, r_raw_data_1, r_raw_data_0};	// @[generators/rocket-chip/src/main/scala/tilelink/SRAM.scala:63:9, :155:30, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
endmodule

