/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/AccPipe.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/AccPipeShared.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/AccumulatorMem.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/AccumulatorScale.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/AlwaysOutTransposer.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Arbiter2_ScratchpadReadReq.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Arbiter2_TLBundleAWithInfo.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Arbiter3_TLBundleAWithInfo.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Arbiter3_UInt6.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Arbiter5_RoCCCommand.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/BeatMerger.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/CounterController.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/CounterFile.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/DMACommandTracker.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/DMACommandTracker_1.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/DTLB_2.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/DecoupledTLB.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ExecuteController.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/FrontendTLB.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Gemmini.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/INToRecFN_i32_e8_s24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/INToRecFN_i8_e8_s24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Im2Col.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoadController.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopConv.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopConvExecute.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopConvLdBias.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopConvLdInput.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopConvLdWeight.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopConvSt.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopMatmul.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopMatmulExecute.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopMatmulLdA.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopMatmulLdB.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopMatmulLdD.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopMatmulStC.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/LoopMatmulStCSpad.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/MacUnit.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Mesh.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/MeshWithDelays.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/MulAddRecFNToRaw_postMul_e8_s24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/MulAddRecFNToRaw_preMul_e8_s24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/MulAddRecFN_e8_s24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/MultiHeadedQueue.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/MultiHeadedQueue_1.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/OptimizationBarrier_TLBEntryData.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/PE.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/PE_256.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/PMAChecker.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/PMPChecker_s6.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Pipeline.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Pipeline_1.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Pipeline_2.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Pipeline_3.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Pipeline_4.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Pipeline_5.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Pipeline_6.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/PixelRepeater.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/PixelRepeater_1.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue1_AccumulatorReadResp.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue1_ScratchpadReadResp.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue1_TLBundleAWithInfo.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue1_TLBundleAWithInfo_2.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue1_TLBundleAWithInfo_3.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_GemminiCmd.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_NormalizedInput.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_ScratchpadMemWriteRequest.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_TLBundleA_a32d128s4k4z4u.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_TLBundleA_a32d128s5k4z4u.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_TLBundleD_a32d128s4k4z4u.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_TLBundleD_a32d128s5k4z4u.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_VectorScalarMultiplierReq.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue2_VectorScalarMultiplierReq_1.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue4_ScratchpadReadResp.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue5_ComputeCntlSignals.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue5_ScratchpadMemReadRequest.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue5_ScratchpadMemWriteRequest.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue5_im2colRowSignals.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue6_ScratchpadMemWriteRequest.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue6_TagWithIdAndTotalRows.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Queue8_GemminiCmd.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RRArbiter.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RRArbiter_4.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RecFNToIN_e8_s24_i32.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RecFNToIN_e8_s24_i8.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ReservationStation.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RoundAnyRawFNToRecFN_ie4_is8_oe8_os24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RoundAnyRawFNToRecFN_ie6_is32_oe8_os24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RoundAnyRawFNToRecFN_ie8_is26_oe8_os24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/RoundRawFNToRecFN_e8_s24.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ScalePipe.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Scratchpad.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ScratchpadBank.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/StoreController.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/StreamReader.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/StreamReaderCore.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/StreamWriter.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLBuffer_a32d128s4k4z4u.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLBuffer_a32d128s4k4z4u_1.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLBuffer_a32d128s5k4z4u.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLMonitor_43.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLMonitor_44.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLMonitor_45.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLMonitor_46.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLMonitor_47.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TLXbar_i2_o1_a32d128s5k4z4u.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TagQueue.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/Tile.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TransposePreloadUnroller.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/TwoPortSyncMem.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/VectorScalarMultiplier.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/VectorScalarMultiplier_1.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/WeightedArbiter.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/XactTracker.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ZeroWriter.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/mem.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/mem_0.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x147.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x148.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x191.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x192.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x257.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x274.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x383.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x550.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_2x625.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_4x129.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_5x190.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_5x258.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_5x88.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_6x383.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_6x8.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/ram_8x246.sv
/home/lisihang/thermal_placement/rtl_exports/generated-verilog/GemminiRocketConfig/gen-collateral/plusarg_reader.v
/home/lisihang/thermal_placement/physical/stage2_tiled_matmul_os_baseline_asap7/src/gemmini_stage2_memory_blackboxes.sv
