#!/usr/bin/env python3
"""Create a first-pass Gemmini module inventory from generated RTL."""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml


MODULE_RE = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)\b", re.MULTILINE)

CATEGORY_RULES: list[tuple[str, str, tuple[str, ...]]] = [
    ("pe_array", "PE array / mesh / compute datapath", ("mesh", "meshwithdelays", "pe", "pe_", "macunit", "systolic", "accpipe", "scalepipe")),
    ("scratchpad", "Scratchpad / local buffer", ("scratchpad", "spad", "sp_bank", "spadmem")),
    ("accumulator", "Accumulator / partial-sum storage", ("accumulator", "accumulatormem", "accumulatorscale", "accbank")),
    ("load_store_dma", "Load/store DMA and memory movement", ("dma", "streamreader", "streamwriter", "loadcontroller", "storecontroller")),
    ("controller", "Command, execute, loop, and scheduling control", ("executecontroller", "countercontroller", "gemminicmd", "reservationstation", "loopmatmul", "unroller", "rob")),
    ("tl_soc_glue", "TileLink / RoCC / SoC glue", ("tilelink", "rocc", "frontend", "memport", "ptw")),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rtl-dir", type=Path, required=True, help="Directory containing generated Verilog/SystemVerilog files")
    parser.add_argument("--hierarchy-json", type=Path, help="Optional Chipyard/CIRCT module hierarchy JSON")
    parser.add_argument("--out-md", type=Path, required=True, help="Markdown inventory output path")
    parser.add_argument("--out-yaml", type=Path, required=True, help="YAML hierarchy-map output path")
    return parser.parse_args()


def read_modules(rtl_dir: Path) -> dict[str, list[str]]:
    modules: dict[str, list[str]] = defaultdict(list)
    for path in sorted(rtl_dir.rglob("*")):
        if path.suffix not in {".v", ".sv"}:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in MODULE_RE.finditer(text):
            modules[match.group(1)].append(str(path))
    return dict(modules)


def keyword_matches(module_name: str, keyword: str) -> bool:
    lowered = module_name.lower()
    keyword = keyword.lower()
    if keyword == "pe":
        return lowered == "pe" or lowered.startswith("pe_")
    if keyword.endswith("_"):
        return lowered.startswith(keyword)
    return keyword in lowered


def category_for(module_name: str) -> str:
    lowered = module_name.lower()
    for category, _description, keywords in CATEGORY_RULES:
        if any(keyword_matches(module_name, keyword) for keyword in keywords):
            return category
    if "gemmini" in lowered:
        return "gemmini_other"
    return "non_gemmini_context"


def load_hierarchy(path: Path | None) -> Any | None:
    if path is None or not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def iter_hierarchy_names(node: Any) -> list[str]:
    names: list[str] = []

    def walk(value: Any) -> None:
        if isinstance(value, dict):
            for key in ("module_name", "module", "name", "class", "instance_name", "instance"):
                found = value.get(key)
                if isinstance(found, str):
                    names.append(found)
            for child_key in ("children", "instances", "modules", "hierarchy"):
                child = value.get(child_key)
                if child is not None:
                    walk(child)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    walk(node)
    return names


def write_markdown(
    out_path: Path,
    modules: dict[str, list[str]],
    categorized: dict[str, list[str]],
    hierarchy_names: list[str],
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# Gemmini Module Inventory",
        "",
        "This file is generated by `scripts/inspect_gemmini_hierarchy.py` from Chipyard/Gemmini RTL collateral.",
        "",
        "## Summary",
        "",
        f"- RTL modules found: {len(modules)}",
        f"- Hierarchy names found: {len(hierarchy_names)}" if hierarchy_names else "- Hierarchy JSON: not available",
        "",
        "## Thermal Study Buckets",
        "",
        "| Bucket | Description | Module Count | Initial Treatment |",
        "| --- | --- | ---: | --- |",
    ]

    descriptions = {category: description for category, description, _keywords in CATEGORY_RULES}
    descriptions["gemmini_other"] = "Other modules with Gemmini in the module name"
    descriptions["non_gemmini_context"] = "Generated SoC/test harness context"

    for category in sorted(categorized):
        treatment = "include" if category not in {"tl_soc_glue", "non_gemmini_context"} else "defer"
        lines.append(
            f"| `{category}` | {descriptions.get(category, category)} | {len(categorized[category])} | {treatment} |"
        )

    lines.extend(["", "## Modules By Bucket", ""])
    for category in sorted(categorized):
        lines.append(f"### {category}")
        lines.append("")
        for module_name in categorized[category]:
            files = modules[module_name]
            rel_files = ", ".join(sorted(Path(f).name for f in files[:3]))
            if len(files) > 3:
                rel_files += f", ... ({len(files)} files)"
            lines.append(f"- `{module_name}` ({rel_files})")
        lines.append("")

    if hierarchy_names:
        lines.extend(["## Hierarchy Name Sample", ""])
        for name in hierarchy_names[:200]:
            lines.append(f"- `{name}`")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def write_yaml(out_path: Path, modules: dict[str, list[str]], categorized: dict[str, list[str]]) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    include_categories = ["pe_array", "scratchpad", "accumulator", "load_store_dma", "controller", "gemmini_other"]
    payload = {
        "source": "generated by scripts/inspect_gemmini_hierarchy.py",
        "notes": [
            "First-pass module map for activity extraction.",
            "Review generated buckets before treating this as a final thermal hierarchy.",
        ],
        "categories": {
            category: {
                "include_in_thermal_study": category in include_categories,
                "modules": categorized.get(category, []),
            }
            for category in sorted(categorized)
        },
        "all_modules": sorted(modules),
    }
    out_path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def main() -> None:
    args = parse_args()
    if not args.rtl_dir.exists():
        raise SystemExit(f"RTL directory does not exist: {args.rtl_dir}")

    modules = read_modules(args.rtl_dir)
    categorized: dict[str, list[str]] = defaultdict(list)
    for module_name in sorted(modules):
        categorized[category_for(module_name)].append(module_name)

    hierarchy = load_hierarchy(args.hierarchy_json)
    hierarchy_names = sorted(set(iter_hierarchy_names(hierarchy))) if hierarchy is not None else []

    write_markdown(args.out_md, modules, dict(categorized), hierarchy_names)
    write_yaml(args.out_yaml, modules, dict(categorized))

    print(f"modules={len(modules)}")
    print(f"wrote {args.out_md}")
    print(f"wrote {args.out_yaml}")


if __name__ == "__main__":
    main()
