#!/usr/bin/env python3
"""Generate script-only Cadence Phase3 mvin_mvout power bring-up collateral.

This command does not launch Innovus. It consumes the completed read-only
preflight manifest and writes Tcl/run notes under power/mvin_mvout/cadence/.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

RUN_ROOT_DEFAULT = Path("runs/GemminiRocketConfig__mesh16x16_tile1x1_dim16__signoff")
R28_TAG = "gemmini_mesh16x16_tile1x1_dim16_asap7sc7p5t28_fake_sram_200mhz_phase2_full_20260513_r28_export_from_routing_sdf_waived"
PHASE1B_TAG = "phase1b_gate_saif_r28_20260515"
WORKLOAD = "mvin_mvout"

try:
    REPO_ROOT = Path(__file__).resolve().parents[1]
except NameError:
    REPO_ROOT = Path.cwd().resolve()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-root", type=Path, default=RUN_ROOT_DEFAULT)
    parser.add_argument("--phase2-run", type=Path, default=None)
    parser.add_argument("--phase1b-root", type=Path, default=None)
    parser.add_argument("--out-dir", type=Path, default=None)
    parser.add_argument("--workload", default=WORKLOAD, choices=[WORKLOAD])
    parser.add_argument("--force", action="store_true", help="overwrite generated script-only collateral")
    return parser.parse_args()


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path.resolve())


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def require_nonempty_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise SystemExit(f"missing required {label}: {rel(path)}")
    if path.stat().st_size <= 0:
        raise SystemExit(f"empty required {label}: {rel(path)}")


def require_nonempty_dir(path: Path, label: str) -> None:
    if not path.is_dir():
        raise SystemExit(f"missing required {label} directory: {rel(path)}")
    try:
        next(path.iterdir())
    except StopIteration as exc:
        raise SystemExit(f"empty required {label} directory: {rel(path)}") from exc


def tcl_quote(path_or_text: str | Path) -> str:
    text = str(path_or_text)
    if "}" in text or "\\" in text:
        return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return "{" + text + "}"


def detect_saif_root(saif: Path) -> str | None:
    with saif.open("r", encoding="utf-8", errors="replace") as handle:
        chunk = handle.read(65536)
    match = re.search(r"\(INSTANCE\s+([^\s()]+)", chunk)
    if not match:
        return None
    return match.group(1)


def write_text(path: Path, text: str, force: bool) -> None:
    if path.exists() and not force:
        raise SystemExit(f"refusing to overwrite existing file without --force: {rel(path)}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build_tcl(paths: dict[str, Path], saif_scope: str, generated_at: str) -> str:
    q = tcl_quote
    return f"""# Generated by scripts/phase3_mvin_mvout_write_cadence_power_scripts.py
# Generated at UTC: {generated_at}
# Stage: Phase3 mvin_mvout Cadence activity-aware power bring-up
# Quality: NON-SIGNOFF. r28 is PG-open / DRC-open / routed-SDF-waived thermal proxy.
# Activity: Verilator zero-delay SAIF, not SDF timing simulation or commercial gate simulation.
# This Tcl is generated only; do not run it unless explicitly approved.

set design_name Gemmini
set workload mvin_mvout
set phase3_root {q(paths['out_dir'].resolve())}
set cadence_root {q(paths['cadence_dir'].resolve())}
set report_dir {q(paths['report_dir'].resolve())}
set log_dir {q(paths['log_dir'].resolve())}
set checkpoint_dat {q(paths['checkpoint_dat'].resolve())}
set saif_file {q(paths['saif'].resolve())}
set saif_scope {q(saif_scope)}

file mkdir $report_dir
file mkdir $log_dir

puts "PHASE3_MVIN_MVOUT_BEGIN non-signoff activity-aware power bring-up"
puts "PHASE3_INPUT checkpoint=$checkpoint_dat"
puts "PHASE3_INPUT saif=$saif_file"
puts "PHASE3_INPUT saif_scope=$saif_scope"

# Keep execution conservative and aligned with the accepted r28 export route.
setMultiCpuUsage -localCpu 1
setAnalysisMode -analysisType single
setDesignMode -topRoutingLayer M8
setDesignMode -bottomRoutingLayer M2
setDelayCalMode -SIAware false

# Restore the exported routed checkpoint read-only. Do not save back into r28.
restoreDesign $checkpoint_dat $design_name

# Apply the formal Phase1b mvin_mvout SAIF. Local Innovus/Voltus docs for 23.14
# expose read_activity_file with -format SAIF; no local read_saif help entry was found.
read_activity_file $saif_file -format SAIF -scope $saif_scope -reset -zero_delay true

# Annotation diagnostics must be inspected before any downstream grid/thermal use.
get_activity -summary -outfile "$report_dir/phase3_mvin_mvout_activity_summary.rpt"
get_activity -report_cell_group_activity_summary_report -outfile "$report_dir/phase3_mvin_mvout_activity_cell_group_summary.rpt"
get_activity -list_of_nets_based_on_source_of_activity_info activity_file -outfile "$report_dir/phase3_mvin_mvout_activity_file_nets.rpt"
get_activity -list_of_nets_based_on_source_of_activity_info default -outfile "$report_dir/phase3_mvin_mvout_default_activity_nets.rpt"
get_activity -list_of_nets_based_on_source_of_activity_info propagated -outfile "$report_dir/phase3_mvin_mvout_propagated_activity_nets.rpt"
dump_unannotated_nets -type saif -file "$report_dir/phase3_mvin_mvout_unannotated_saif_nets.rpt"
dump_unannotated_nets -type all -file "$report_dir/phase3_mvin_mvout_unannotated_all_nets.rpt"

# Average power reports for initial bring-up. Later grid mapping should consume
# these only after annotation coverage is accepted.
report_power -hierarchy all -outfile "$report_dir/phase3_mvin_mvout_power_hierarchy.rpt"
report_power -instances {{*}} -outfile "$report_dir/phase3_mvin_mvout_power_instances.rpt"
report_power -net -nworst 200 -outfile "$report_dir/phase3_mvin_mvout_power_top_nets.rpt"

puts "PHASE3_MVIN_MVOUT_DONE reports=$report_dir"
exit
"""


def shell_quote(path_or_text: str | Path) -> str:
    return shlex.quote(str(path_or_text))


def build_runner(paths: dict[str, Path]) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

# Generated helper only. Run this only after explicit approval.
# It launches Innovus no-GUI on the generated non-signoff Phase3 mvin_mvout Tcl.
cd {shell_quote(REPO_ROOT)}
source tools/env_gemmini_thermal.sh
innovus -no_gui -files {shell_quote(paths['tcl'].resolve())} -log {shell_quote(paths['log_dir'].resolve() / 'phase3_mvin_mvout_innovus.log')}
"""


def build_readme(paths: dict[str, Path], saif_scope: str) -> str:
    return f"""# Phase3 mvin_mvout Cadence Script-Only Plan

Generated: {utc_now()}

This directory contains generated Cadence collateral for the user-confirmed single-workload `mvin_mvout` Phase3 bring-up. It has not launched Innovus.

Quality labels:

- NON-SIGNOFF downstream result.
- Stage2 r28 input is `PG-open / DRC-open / routed-SDF-waived thermal proxy`.
- Phase1b SAIF input is Verilator zero-delay activity, not SDF timing simulation and not commercial gate simulation.

Key input decisions:

- SAIF: `{rel(paths['saif'])}`
- SAIF root scope detected from file: `{saif_scope}`
- Cadence activity command: `read_activity_file -format SAIF -scope {saif_scope}`
- Checkpoint restore input: `{rel(paths['checkpoint_dat'])}`

Generated files:

- `{rel(paths['tcl'])}`
- `{rel(paths['runner'])}`
- `{rel(paths['manifest'])}`

The runner is intentionally generated but not executed. Before using reports for grid or thermal work, inspect the activity summary and unannotated-net reports produced by the Tcl.
"""


def main() -> int:
    args = parse_args()
    run_root = args.run_root
    phase2 = args.phase2_run or run_root / "physical" / R28_TAG
    phase1b = args.phase1b_root or run_root / "gate_activity" / PHASE1B_TAG
    out_dir = args.out_dir or run_root / "power" / WORKLOAD
    cadence_dir = out_dir / "cadence"
    script_dir = cadence_dir / "scripts"
    report_dir = cadence_dir / "reports"
    log_dir = cadence_dir / "logs"

    preflight_manifest = out_dir / "phase3_mvin_mvout_preflight_manifest.json"
    require_nonempty_file(preflight_manifest, "Phase3 preflight manifest")
    preflight = read_json(preflight_manifest)
    if preflight.get("status") not in {"pass", "pass_with_warnings"}:
        raise SystemExit(f"preflight status is not usable: {preflight.get('status')}")

    saif = phase1b / WORKLOAD / f"{WORKLOAD}.gate.saif"
    workload_manifest = phase1b / WORKLOAD / "gate_activity_manifest.json"
    replay_summary = phase1b / WORKLOAD / "replay_summary.json"
    checkpoint_dat = phase2 / "innovus" / "data" / "export_routing.enc.dat"
    export_checkpoint = phase2 / "innovus" / "data" / "export_routing.enc"
    for path, label in [
        (saif, "mvin_mvout SAIF"),
        (workload_manifest, "mvin_mvout gate activity manifest"),
        (replay_summary, "mvin_mvout replay summary"),
        (export_checkpoint, "r28 export_routing.enc"),
    ]:
        require_nonempty_file(path, label)
    require_nonempty_dir(checkpoint_dat, "r28 export_routing.enc.dat")

    workload_data = read_json(workload_manifest)
    replay_data = read_json(replay_summary)
    if workload_data.get("phase3_consumable") is not True:
        raise SystemExit("mvin_mvout gate_activity_manifest.json is not phase3_consumable=true")
    if replay_data.get("run_returncode") != 0:
        raise SystemExit("mvin_mvout replay_summary.json does not have run_returncode=0")

    saif_scope = detect_saif_root(saif)
    if not saif_scope:
        raise SystemExit(f"could not detect first SAIF INSTANCE scope in {rel(saif)}")

    paths = {
        "run_root": run_root,
        "phase2": phase2,
        "phase1b": phase1b,
        "out_dir": out_dir,
        "cadence_dir": cadence_dir,
        "script_dir": script_dir,
        "report_dir": report_dir,
        "log_dir": log_dir,
        "saif": saif,
        "checkpoint_dat": checkpoint_dat,
        "export_checkpoint": export_checkpoint,
        "tcl": script_dir / "phase3_mvin_mvout_read_activity_power.tcl",
        "runner": script_dir / "run_phase3_mvin_mvout_innovus_no_gui.sh",
        "manifest": cadence_dir / "phase3_mvin_mvout_cadence_script_manifest.json",
        "readme": cadence_dir / "README.md",
    }
    generated_at = utc_now()

    manifest: dict[str, Any] = {
        "schema": "phase3_mvin_mvout_cadence_script_manifest_v1",
        "generated_at_utc": generated_at,
        "status": "script_only_generated",
        "workload": WORKLOAD,
        "no_cadence_launched": True,
        "non_signoff_label": "PG-open / DRC-open / routed-SDF-waived thermal proxy; Phase1b SAIF is Verilator zero-delay activity",
        "preflight_manifest": rel(preflight_manifest),
        "inputs": {
            "saif": {"path": rel(saif), "bytes": saif.stat().st_size, "scope": saif_scope},
            "gate_activity_manifest": rel(workload_manifest),
            "replay_summary": rel(replay_summary),
            "checkpoint_dat": {"path": rel(checkpoint_dat), "type": "directory"},
            "checkpoint_tcl": rel(export_checkpoint),
        },
        "cadence_method": {
            "restore_command": "restoreDesign <export_routing.enc.dat> Gemmini",
            "activity_command": f"read_activity_file <saif> -format SAIF -scope {saif_scope} -reset -zero_delay true",
            "command_basis": "Local Innovus/Voltus 23.14 docs expose read_activity_file with -format SAIF; no local read_saif help entry was found.",
            "reports_before_handoff": [
                "get_activity -summary",
                "get_activity -report_cell_group_activity_summary_report",
                "dump_unannotated_nets -type saif",
                "dump_unannotated_nets -type all",
                "report_power -hierarchy all",
                "report_power -instances {*}"
            ],
        },
        "outputs": {
            "cadence_dir": rel(cadence_dir),
            "tcl": rel(paths["tcl"]),
            "runner": rel(paths["runner"]),
            "readme": rel(paths["readme"]),
            "reports_dir_when_run": rel(report_dir),
            "logs_dir_when_run": rel(log_dir),
        },
        "excluded": {
            "ws_os": "not in current user-confirmed Phase3 mvin-only bring-up scope",
            "accelerated_replays": "still not adopted as default Phase3 handoff method",
            "smoke_and_old_compare": "not Phase3 handoff inputs",
        },
    }

    write_text(paths["tcl"], build_tcl(paths, saif_scope, generated_at), args.force)
    write_text(paths["runner"], build_runner(paths), args.force)
    paths["runner"].chmod(0o755)
    write_text(paths["readme"], build_readme(paths, saif_scope), args.force)
    write_text(paths["manifest"], json.dumps(manifest, indent=2, sort_keys=True) + "\n", args.force)

    print(json.dumps({"status": "script_only_generated", "manifest": rel(paths["manifest"]), "tcl": rel(paths["tcl"]), "runner": rel(paths["runner"]), "saif_scope": saif_scope}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
