// Generated by CIRCT firtool-1.75.0
module INToRecFN_i8_e8_s24(	// @[generators/hardfloat/hardfloat/src/main/scala/INToRecFN.scala:43:7]
  input  [7:0]  io_in,	// @[generators/hardfloat/hardfloat/src/main/scala/INToRecFN.scala:46:16]
  output [32:0] io_out	// @[generators/hardfloat/hardfloat/src/main/scala/INToRecFN.scala:46:16]
);

  wire [7:0]  intAsRawFloat_absIn = io_in[7] ? 8'h0 - io_in : io_in;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromIN.scala:51:34, :52:{24,31}]
  wire [2:0]  intAsRawFloat_adjustedNormDist = intAsRawFloat_absIn[7] ? 3'h0 : intAsRawFloat_absIn[6] ? 3'h1 : intAsRawFloat_absIn[5] ? 3'h2 : intAsRawFloat_absIn[4] ? 3'h3 : intAsRawFloat_absIn[3] ? 3'h4 : intAsRawFloat_absIn[2] ? 3'h5 : {2'h3, ~(intAsRawFloat_absIn[1])};	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromIN.scala:52:24, :53:53, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [14:0] _intAsRawFloat_sig_T = {7'h0, intAsRawFloat_absIn} << intAsRawFloat_adjustedNormDist;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromIN.scala:52:24, :56:22, src/main/scala/chisel3/util/Mux.scala:50:70]
  RoundAnyRawFNToRecFN_ie4_is8_oe8_os24 roundAnyRawFNToRecFN (	// @[generators/hardfloat/hardfloat/src/main/scala/INToRecFN.scala:60:15]
    .io_in_isZero (~(_intAsRawFloat_sig_T[7])),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromIN.scala:56:{22,41}, :62:{23,28}]
    .io_in_sign   (io_in[7]),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromIN.scala:51:34]
    .io_in_sExp   ({3'h2, ~intAsRawFloat_adjustedNormDist}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromIN.scala:64:{36,72}, src/main/scala/chisel3/util/Mux.scala:50:70]
    .io_in_sig    ({1'h0, _intAsRawFloat_sig_T[7:0]}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromIN.scala:52:31, :56:{22,41}, :65:20]
    .io_out       (io_out)
  );	// @[generators/hardfloat/hardfloat/src/main/scala/INToRecFN.scala:60:15]
endmodule

