// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LoopConvLdBias(	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
  output        io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input         io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input  [15:0] io_req_bits_inner_bounds_batches,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input  [15:0] io_req_bits_inner_bounds_orows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input  [15:0] io_req_bits_inner_bounds_ocols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input  [15:0] io_req_bits_derived_params_ochs,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input  [15:0] io_req_bits_derived_params_bias_spad_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input  [9:0]  io_req_bits_addr_start,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input  [39:0] io_req_bits_dram_addr,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input         io_req_bits_no_bias,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input         io_req_bits_loop_id,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input         io_cmd_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  output        io_cmd_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  output [6:0]  io_cmd_bits_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  output [63:0] io_cmd_bits_rs1,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  output [63:0] io_cmd_bits_rs2,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  output        io_idle,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input         io_rob_overloaded,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  input         io_wait_for_prev_loop,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
  output        io_loop_id	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:88:14]
);

  wire        _command_p_io_in_ready;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire        _command_p_io_out_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire [6:0]  _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire [63:0] _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire [39:0] _command_p_io_out_bits_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire [67:0] _command_p_io_out_bits_spad_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire [15:0] _command_p_io_out_bits_I;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire [15:0] _command_p_io_out_bits_J;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  wire        _command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  reg  [1:0]  state;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22]
  reg  [15:0] req_inner_bounds_batches;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg  [15:0] req_inner_bounds_orows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg  [15:0] req_inner_bounds_ocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg  [15:0] req_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg  [15:0] req_derived_params_bias_spad_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg  [9:0]  req_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg  [39:0] req_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg         req_no_bias;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  reg         req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
  wire [15:0] max_ochs_per_mvin = req_derived_params_ochs < 16'h10 ? req_derived_params_ochs : 16'h10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :112:{30,36}]
  reg  [15:0] b;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:117:14]
  reg  [15:0] orow;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:118:17]
  reg  [15:0] ocol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:119:17]
  reg  [15:0] och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:120:16]
  wire [15:0] _I_T_3 = req_inner_bounds_ocols - ocol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :119:17, :128:21]
  wire [15:0] _J_T_3 = req_derived_params_ochs - och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :120:16, :129:20]
  wire        _io_idle_T = state == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22, :164:25]
  wire        io_req_ready_0 = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25, :164:{25,34,37}]
  wire        command_p_io_in_valid = (|state) & ~io_wait_for_prev_loop & (|req_dram_addr);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22, :105:16, :114:28, :168:{34,43,46,69}]
  wire        _command_p_io_in_bits_cmd_T = state == 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22, :152:26, :169:41]
  wire        _GEN = _command_p_io_out_bits_cmd_inst_funct == 7'hE;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25, :159:23, :178:46]
  wire        _GEN_0 = _command_p_io_in_ready & command_p_io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25, :168:{43,69}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [16:0] _next_och_T_3 = {1'h0, och} + {1'h0, max_ochs_per_mvin};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:112:30, :120:16, :129:20, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] next_och = _next_och_T_3 > {1'h0, req_derived_params_ochs - 16'h1} ? 16'h0 : _next_och_T_3[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_ocol_T_4 = {1'h0, ocol} + 17'h10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:119:17, :128:21, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_ocol_T_6 = _next_ocol_T_4 > {1'h0, req_inner_bounds_ocols - 16'h1} ? 16'h0 : _next_ocol_T_4[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_3 = ((|next_och) ? ocol : _next_ocol_T_6) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:119:17, :197:68, :198:60, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_orow_T_2 = _state_T_3 & ~(|next_och);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:197:68, :198:{60,68}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_orow_T_6 = {1'h0, orow} + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:118:17, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_orow_T_8 = _next_orow_T_6 > {1'h0, req_inner_bounds_orows - 16'h1} ? 16'h0 : _next_orow_T_6[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_1 = (_next_orow_T_2 ? _next_orow_T_8 : orow) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:118:17, :198:68, :199:56, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_b_T_4 = _state_T_1 & _state_T_3 & ~(|next_och);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:197:68, :198:60, :199:{56,64,85}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_b_T_8 = {1'h0, b} + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:117:14, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_b_T_10 = _next_b_T_8 > {1'h0, req_inner_bounds_batches - 16'h1} ? 16'h0 : _next_b_T_8[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_1 = io_req_ready_0 & io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:164:34, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
    if (reset)	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
      state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22]
    else if (_GEN_1)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      state <= 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22, :152:26]
    else if (|req_dram_addr) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :114:28]
      if (_GEN_0)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        state <= _command_p_io_in_bits_cmd_T ? 2'h2 : {~((_next_b_T_4 ? _next_b_T_10 : b) == 16'h0 & _state_T_1 & _state_T_3 & ~(|next_och)), 1'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22, :117:14, :169:41, :193:29, :194:13, :197:68, :198:60, :199:{56,64,85}, :206:{13,19,27,35,56,77}, src/main/scala/chisel3/util/Mux.scala:126:16]
    end
    else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:114:28]
      state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:103:22]
    if (_GEN_1) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_inner_bounds_batches <= io_req_bits_inner_bounds_batches;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_inner_bounds_orows <= io_req_bits_inner_bounds_orows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_inner_bounds_ocols <= io_req_bits_inner_bounds_ocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_derived_params_ochs <= io_req_bits_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_derived_params_bias_spad_stride <= io_req_bits_derived_params_bias_spad_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_addr_start <= io_req_bits_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_dram_addr <= io_req_bits_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_no_bias <= io_req_bits_no_bias;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      req_loop_id <= io_req_bits_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16]
      b <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:117:14]
      orow <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:118:17]
      ocol <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:119:17]
      och <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:120:16]
    end
    else begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (~(|req_dram_addr) | ~_GEN_0 | _command_p_io_in_bits_cmd_T | ~_next_b_T_4) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :114:28, :117:14, :120:16, :169:41, :190:15, :192:36, :193:29, :199:{64,85}, :204:9, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:117:14, :190:15, :192:36, :193:29, :204:9, src/main/scala/chisel3/util/Mux.scala:126:16]
        b <= _next_b_T_10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:117:14, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~(|req_dram_addr) | ~_GEN_0 | _command_p_io_in_bits_cmd_T | ~_next_orow_T_2) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :114:28, :118:17, :120:16, :169:41, :190:15, :192:36, :193:29, :198:68, :203:12, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:118:17, :190:15, :192:36, :193:29, :203:12, src/main/scala/chisel3/util/Mux.scala:126:16]
        orow <= _next_orow_T_8;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:118:17, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~(|req_dram_addr) | ~_GEN_0 | (|{_command_p_io_in_bits_cmd_T, next_och})) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :114:28, :119:17, :120:16, :169:41, :190:15, :192:36, :193:29, :197:68, :202:12, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:119:17, :190:15, :192:36, :193:29]
        ocol <= _next_ocol_T_6;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:119:17, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~(|req_dram_addr) | ~_GEN_0 | _command_p_io_in_bits_cmd_T) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :114:28, :120:16, :169:41, :190:15, :192:36, :193:29, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:120:16, :190:15, :192:36, :193:29]
        och <= next_och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:120:16, src/main/scala/chisel3/util/Mux.scala:126:16]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:27];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
        for (logic [4:0] i = 5'h0; i < 5'h1C; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
        state = _RANDOM[5'h0][1:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :103:22]
        req_inner_bounds_batches = {_RANDOM[5'h9][31:18], _RANDOM[5'hA][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_inner_bounds_orows = _RANDOM[5'h11][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_inner_bounds_ocols = {_RANDOM[5'h11][31:18], _RANDOM[5'h12][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_derived_params_ochs = _RANDOM[5'h12][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_derived_params_bias_spad_stride = _RANDOM[5'h16][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_addr_start = _RANDOM[5'h17][27:18];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_dram_addr = {_RANDOM[5'h17][31:28], _RANDOM[5'h18], _RANDOM[5'h19][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_no_bias = _RANDOM[5'h19][4];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        req_loop_id = _RANDOM[5'h19][5];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
        b = _RANDOM[5'h19][21:6];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16, :117:14]
        orow = {_RANDOM[5'h19][31:22], _RANDOM[5'h1A][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16, :118:17]
        ocol = _RANDOM[5'h1A][21:6];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :118:17, :119:17]
        och = {_RANDOM[5'h1A][31:22], _RANDOM[5'h1B][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :118:17, :120:16]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Pipeline_2 command_p (	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_ready                (_command_p_io_in_ready),
    .io_in_valid                (command_p_io_in_valid),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:168:{43,69}]
    .io_in_bits_cmd_inst_funct  (_command_p_io_in_bits_cmd_T ? 7'h0 : 7'hE),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:159:23, :169:{34,41}]
    .io_in_bits_cmd_rs1         (_command_p_io_in_bits_cmd_T ? {34'hFE000000, req_derived_params_bias_spad_stride[13:0], 16'h111} : 64'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :148:25, :153:36, :169:{34,41}]
    .io_in_bits_dram_addr       (req_no_bias ? 40'h0 : {22'h0, och, 2'h0} + req_dram_addr),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :120:16, :124:{22,55}, :1556:17]
    .io_in_bits_spad_addr       ({1'h0, {1'h0, {1'h0, {55'h0, req_addr_start} + {1'h0, {16'h0, {16'h0, {16'h0, och / 16'h10} * {16'h0, req_inner_bounds_batches}} * {32'h0, req_inner_bounds_orows}} * {48'h0, req_inner_bounds_ocols}}} + {18'h0, {16'h0, {16'h0, b} * {16'h0, req_inner_bounds_orows}} * {32'h0, req_inner_bounds_ocols}}} + {35'h0, {16'h0, orow} * {16'h0, req_inner_bounds_ocols}}} + {52'h0, ocol}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:105:16, :112:36, :117:14, :118:17, :119:17, :120:16, :125:{34,42,74,84,92,100,105,113,121,129,137}]
    .io_in_bits_I               (_I_T_3 > 16'h10 ? 16'h10 : _I_T_3),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:112:36, :128:{14,21,28}]
    .io_in_bits_J               (_J_T_3 > max_ochs_per_mvin ? max_ochs_per_mvin : _J_T_3),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:112:30, :129:{14,20,26}]
    .io_out_ready               (io_cmd_ready & ~io_rob_overloaded),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:175:{42,45}]
    .io_out_valid               (_command_p_io_out_valid),
    .io_out_bits_cmd_inst_funct (_command_p_io_out_bits_cmd_inst_funct),
    .io_out_bits_cmd_rs1        (_command_p_io_out_bits_cmd_rs1),
    .io_out_bits_dram_addr      (_command_p_io_out_bits_dram_addr),
    .io_out_bits_spad_addr      (_command_p_io_out_bits_spad_addr),
    .io_out_bits_I              (_command_p_io_out_bits_I),
    .io_out_bits_J              (_command_p_io_out_bits_J),
    .io_busy                    (_command_p_io_busy)
  );	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:138:25]
  assign io_req_ready = io_req_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :164:34]
  assign io_cmd_valid = _command_p_io_out_valid & ~io_rob_overloaded;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :138:25, :175:45, :176:42]
  assign io_cmd_bits_inst_funct = _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :138:25]
  assign io_cmd_bits_rs1 = _GEN ? {24'h0, _command_p_io_out_bits_dram_addr} : _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :138:25, :177:15, :178:{46,61}, :180:21]
  assign io_cmd_bits_rs2 = _GEN ? {11'h0, _command_p_io_out_bits_I[4:0], 9'h0, _command_p_io_out_bits_J[6:0], 3'h4, _command_p_io_out_bits_spad_addr[28:26], 11'h0, _command_p_io_out_bits_spad_addr[14:0]} : 64'h0;	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:108:37, generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :138:25, :177:15, :178:{46,61}, :183:27, :184:27, :186:{21,37}]
  assign io_idle = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :138:25, :164:{25,37}, :165:29]
  assign io_loop_id = req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:84:7, :105:16]
endmodule

