// Generated by CIRCT firtool-1.75.0
module RoccCommandRouter(	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7]
  output        io_in_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [6:0]  io_in_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [4:0]  io_in_bits_inst_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [4:0]  io_in_bits_inst_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_inst_xd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_inst_xs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_inst_xs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [4:0]  io_in_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [6:0]  io_in_bits_inst_opcode,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [63:0] io_in_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [63:0] io_in_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_debug,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_cease,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_wfi,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [31:0] io_in_bits_status_isa,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_dprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_dv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_prv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_v,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mpv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_gva,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_tsr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_tw,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_tvm,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mxr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_sum,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_fs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_mpp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_spp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mpie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_spie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_sie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_out_0_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [6:0]  io_out_0_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [4:0]  io_out_0_bits_inst_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [4:0]  io_out_0_bits_inst_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_inst_xd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_inst_xs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_inst_xs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [4:0]  io_out_0_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [6:0]  io_out_0_bits_inst_opcode,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [63:0] io_out_0_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [63:0] io_out_0_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_debug,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_cease,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_wfi,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [31:0] io_out_0_bits_status_isa,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_dprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_dv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_prv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_v,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_sd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [22:0] io_out_0_bits_status_zero2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_mpv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_gva,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_mbe,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_sbe,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_sxl,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_uxl,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_sd_rv32,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [7:0]  io_out_0_bits_status_zero1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_tsr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_tw,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_tvm,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_mxr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_sum,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_mprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_xs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_fs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_mpp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [1:0]  io_out_0_bits_status_vs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_spp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_mpie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_ube,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_spie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_upie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_mie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_hie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_sie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_bits_status_uie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_busy	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
);

  wire       _cmd_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [6:0] _cmd_q_io_deq_bits_inst_opcode;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire       cmdReadys_me = _cmd_q_io_deq_bits_inst_opcode == 7'h7B;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue2_RoCCCommand cmd_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_ready               (io_in_ready),
    .io_enq_valid               (io_in_valid),
    .io_enq_bits_inst_funct     (io_in_bits_inst_funct),
    .io_enq_bits_inst_rs2       (io_in_bits_inst_rs2),
    .io_enq_bits_inst_rs1       (io_in_bits_inst_rs1),
    .io_enq_bits_inst_xd        (io_in_bits_inst_xd),
    .io_enq_bits_inst_xs1       (io_in_bits_inst_xs1),
    .io_enq_bits_inst_xs2       (io_in_bits_inst_xs2),
    .io_enq_bits_inst_rd        (io_in_bits_inst_rd),
    .io_enq_bits_inst_opcode    (io_in_bits_inst_opcode),
    .io_enq_bits_rs1            (io_in_bits_rs1),
    .io_enq_bits_rs2            (io_in_bits_rs2),
    .io_enq_bits_status_debug   (io_in_bits_status_debug),
    .io_enq_bits_status_cease   (io_in_bits_status_cease),
    .io_enq_bits_status_wfi     (io_in_bits_status_wfi),
    .io_enq_bits_status_isa     (io_in_bits_status_isa),
    .io_enq_bits_status_dprv    (io_in_bits_status_dprv),
    .io_enq_bits_status_dv      (io_in_bits_status_dv),
    .io_enq_bits_status_prv     (io_in_bits_status_prv),
    .io_enq_bits_status_v       (io_in_bits_status_v),
    .io_enq_bits_status_mpv     (io_in_bits_status_mpv),
    .io_enq_bits_status_gva     (io_in_bits_status_gva),
    .io_enq_bits_status_tsr     (io_in_bits_status_tsr),
    .io_enq_bits_status_tw      (io_in_bits_status_tw),
    .io_enq_bits_status_tvm     (io_in_bits_status_tvm),
    .io_enq_bits_status_mxr     (io_in_bits_status_mxr),
    .io_enq_bits_status_sum     (io_in_bits_status_sum),
    .io_enq_bits_status_mprv    (io_in_bits_status_mprv),
    .io_enq_bits_status_fs      (io_in_bits_status_fs),
    .io_enq_bits_status_mpp     (io_in_bits_status_mpp),
    .io_enq_bits_status_spp     (io_in_bits_status_spp),
    .io_enq_bits_status_mpie    (io_in_bits_status_mpie),
    .io_enq_bits_status_spie    (io_in_bits_status_spie),
    .io_enq_bits_status_mie     (io_in_bits_status_mie),
    .io_enq_bits_status_sie     (io_in_bits_status_sie),
    .io_deq_ready               (io_out_0_ready & cmdReadys_me),	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, :413:15]
    .io_deq_valid               (_cmd_q_io_deq_valid),
    .io_deq_bits_inst_funct     (io_out_0_bits_inst_funct),
    .io_deq_bits_inst_rs2       (io_out_0_bits_inst_rs2),
    .io_deq_bits_inst_rs1       (io_out_0_bits_inst_rs1),
    .io_deq_bits_inst_xd        (io_out_0_bits_inst_xd),
    .io_deq_bits_inst_xs1       (io_out_0_bits_inst_xs1),
    .io_deq_bits_inst_xs2       (io_out_0_bits_inst_xs2),
    .io_deq_bits_inst_rd        (io_out_0_bits_inst_rd),
    .io_deq_bits_inst_opcode    (_cmd_q_io_deq_bits_inst_opcode),
    .io_deq_bits_rs1            (io_out_0_bits_rs1),
    .io_deq_bits_rs2            (io_out_0_bits_rs2),
    .io_deq_bits_status_debug   (io_out_0_bits_status_debug),
    .io_deq_bits_status_cease   (io_out_0_bits_status_cease),
    .io_deq_bits_status_wfi     (io_out_0_bits_status_wfi),
    .io_deq_bits_status_isa     (io_out_0_bits_status_isa),
    .io_deq_bits_status_dprv    (io_out_0_bits_status_dprv),
    .io_deq_bits_status_dv      (io_out_0_bits_status_dv),
    .io_deq_bits_status_prv     (io_out_0_bits_status_prv),
    .io_deq_bits_status_v       (io_out_0_bits_status_v),
    .io_deq_bits_status_sd      (io_out_0_bits_status_sd),
    .io_deq_bits_status_zero2   (io_out_0_bits_status_zero2),
    .io_deq_bits_status_mpv     (io_out_0_bits_status_mpv),
    .io_deq_bits_status_gva     (io_out_0_bits_status_gva),
    .io_deq_bits_status_mbe     (io_out_0_bits_status_mbe),
    .io_deq_bits_status_sbe     (io_out_0_bits_status_sbe),
    .io_deq_bits_status_sxl     (io_out_0_bits_status_sxl),
    .io_deq_bits_status_uxl     (io_out_0_bits_status_uxl),
    .io_deq_bits_status_sd_rv32 (io_out_0_bits_status_sd_rv32),
    .io_deq_bits_status_zero1   (io_out_0_bits_status_zero1),
    .io_deq_bits_status_tsr     (io_out_0_bits_status_tsr),
    .io_deq_bits_status_tw      (io_out_0_bits_status_tw),
    .io_deq_bits_status_tvm     (io_out_0_bits_status_tvm),
    .io_deq_bits_status_mxr     (io_out_0_bits_status_mxr),
    .io_deq_bits_status_sum     (io_out_0_bits_status_sum),
    .io_deq_bits_status_mprv    (io_out_0_bits_status_mprv),
    .io_deq_bits_status_xs      (io_out_0_bits_status_xs),
    .io_deq_bits_status_fs      (io_out_0_bits_status_fs),
    .io_deq_bits_status_mpp     (io_out_0_bits_status_mpp),
    .io_deq_bits_status_vs      (io_out_0_bits_status_vs),
    .io_deq_bits_status_spp     (io_out_0_bits_status_spp),
    .io_deq_bits_status_mpie    (io_out_0_bits_status_mpie),
    .io_deq_bits_status_ube     (io_out_0_bits_status_ube),
    .io_deq_bits_status_spie    (io_out_0_bits_status_spie),
    .io_deq_bits_status_upie    (io_out_0_bits_status_upie),
    .io_deq_bits_status_mie     (io_out_0_bits_status_mie),
    .io_deq_bits_status_hie     (io_out_0_bits_status_hie),
    .io_deq_bits_status_sie     (io_out_0_bits_status_sie),
    .io_deq_bits_status_uie     (io_out_0_bits_status_uie)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_0_valid = _cmd_q_io_deq_valid & cmdReadys_me;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, :400:7, :411:28, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_0_bits_inst_opcode = _cmd_q_io_deq_bits_inst_opcode;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_busy = _cmd_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
endmodule

