// Generated by CIRCT firtool-1.75.0
module RRArbiter_5(	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  output        io_in_0_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  input         io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  input  [4:0]  io_in_0_bits_rd,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  input  [63:0] io_in_0_bits_data,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  input         io_out_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  output        io_out_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  output [4:0]  io_out_bits_rd,	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
  output [63:0] io_out_bits_data	// @[src/main/scala/chisel3/util/Arbiter.scala:52:14]
);

  assign io_in_0_ready = io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  assign io_out_valid = io_in_0_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  assign io_out_bits_rd = io_in_0_bits_rd;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
  assign io_out_bits_data = io_in_0_bits_data;	// @[src/main/scala/chisel3/util/Arbiter.scala:118:7]
endmodule

