// Generated by CIRCT firtool-1.75.0
module SerialTL0ClockSinkDomain(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  input         auto_serdesser_client_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_serdesser_client_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_serdesser_client_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_serdesser_client_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_serdesser_client_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_serdesser_client_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_serdesser_client_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_serdesser_client_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_serdesser_client_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_serdesser_client_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_serdesser_client_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_serdesser_client_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_serdesser_client_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_serdesser_client_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_serdesser_client_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_serdesser_client_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_serdesser_client_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_serdesser_client_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_serdesser_client_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_serdesser_client_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_clock_in_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        serial_tl_0_in_ready,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:165:24]
  input         serial_tl_0_in_valid,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:165:24]
  input  [31:0] serial_tl_0_in_bits_phit,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:165:24]
  input         serial_tl_0_out_ready,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:165:24]
  output        serial_tl_0_out_valid,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:165:24]
  output [31:0] serial_tl_0_out_bits_phit,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:165:24]
  input         serial_tl_0_clock_in	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:165:24]
);

  wire        _phy_io_outer_reset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire        _phy_io_inner_ser_0_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire [31:0] _phy_io_inner_ser_0_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire        _phy_io_inner_ser_1_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire [31:0] _phy_io_inner_ser_1_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire        _phy_io_inner_ser_1_out_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire        _phy_io_inner_ser_2_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire [31:0] _phy_io_inner_ser_2_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire        _phy_io_inner_ser_3_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire [31:0] _phy_io_inner_ser_3_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire        _phy_io_inner_ser_3_out_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire        _phy_io_inner_ser_4_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire [31:0] _phy_io_inner_ser_4_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  wire        _serdesser_io_ser_0_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_1_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_1_out_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire [31:0] _serdesser_io_ser_1_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_2_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_3_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_3_out_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire [31:0] _serdesser_io_ser_3_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_4_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  TLSerdesser_serial_tl_0 serdesser (	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .clock                          (auto_clock_in_clock),
    .reset                          (auto_clock_in_reset),
    .auto_client_out_a_ready        (auto_serdesser_client_out_a_ready),
    .auto_client_out_a_valid        (auto_serdesser_client_out_a_valid),
    .auto_client_out_a_bits_opcode  (auto_serdesser_client_out_a_bits_opcode),
    .auto_client_out_a_bits_param   (auto_serdesser_client_out_a_bits_param),
    .auto_client_out_a_bits_size    (auto_serdesser_client_out_a_bits_size),
    .auto_client_out_a_bits_source  (auto_serdesser_client_out_a_bits_source),
    .auto_client_out_a_bits_address (auto_serdesser_client_out_a_bits_address),
    .auto_client_out_a_bits_mask    (auto_serdesser_client_out_a_bits_mask),
    .auto_client_out_a_bits_data    (auto_serdesser_client_out_a_bits_data),
    .auto_client_out_a_bits_corrupt (auto_serdesser_client_out_a_bits_corrupt),
    .auto_client_out_d_ready        (auto_serdesser_client_out_d_ready),
    .auto_client_out_d_valid        (auto_serdesser_client_out_d_valid),
    .auto_client_out_d_bits_opcode  (auto_serdesser_client_out_d_bits_opcode),
    .auto_client_out_d_bits_param   (auto_serdesser_client_out_d_bits_param),
    .auto_client_out_d_bits_size    (auto_serdesser_client_out_d_bits_size),
    .auto_client_out_d_bits_source  (auto_serdesser_client_out_d_bits_source),
    .auto_client_out_d_bits_sink    (auto_serdesser_client_out_d_bits_sink),
    .auto_client_out_d_bits_denied  (auto_serdesser_client_out_d_bits_denied),
    .auto_client_out_d_bits_data    (auto_serdesser_client_out_d_bits_data),
    .auto_client_out_d_bits_corrupt (auto_serdesser_client_out_d_bits_corrupt),
    .io_ser_0_in_ready              (_serdesser_io_ser_0_in_ready),
    .io_ser_0_in_valid              (_phy_io_inner_ser_0_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_0_in_bits_flit          (_phy_io_inner_ser_0_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_1_in_ready              (_serdesser_io_ser_1_in_ready),
    .io_ser_1_in_valid              (_phy_io_inner_ser_1_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_1_in_bits_flit          (_phy_io_inner_ser_1_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_1_out_ready             (_phy_io_inner_ser_1_out_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_1_out_valid             (_serdesser_io_ser_1_out_valid),
    .io_ser_1_out_bits_flit         (_serdesser_io_ser_1_out_bits_flit),
    .io_ser_2_in_ready              (_serdesser_io_ser_2_in_ready),
    .io_ser_2_in_valid              (_phy_io_inner_ser_2_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_2_in_bits_flit          (_phy_io_inner_ser_2_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_3_in_ready              (_serdesser_io_ser_3_in_ready),
    .io_ser_3_in_valid              (_phy_io_inner_ser_3_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_3_in_bits_flit          (_phy_io_inner_ser_3_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_3_out_ready             (_phy_io_inner_ser_3_out_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_3_out_valid             (_serdesser_io_ser_3_out_valid),
    .io_ser_3_out_bits_flit         (_serdesser_io_ser_3_out_bits_flit),
    .io_ser_4_in_ready              (_serdesser_io_ser_4_in_ready),
    .io_ser_4_in_valid              (_phy_io_inner_ser_4_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_ser_4_in_bits_flit          (_phy_io_inner_ser_4_in_bits_flit)	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  );	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  ResetCatchAndSync_d3 outer_reset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (serial_tl_0_clock_in),
    .reset         (auto_clock_in_reset),
    .io_sync_reset (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  DecoupledSerialPhy phy (	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
    .io_outer_clock               (serial_tl_0_clock_in),
    .io_outer_reset               (_phy_io_outer_reset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_inner_clock               (auto_clock_in_clock),
    .io_inner_reset               (auto_clock_in_reset),
    .io_outer_ser_in_ready        (serial_tl_0_in_ready),
    .io_outer_ser_in_valid        (serial_tl_0_in_valid),
    .io_outer_ser_in_bits_phit    (serial_tl_0_in_bits_phit),
    .io_outer_ser_out_ready       (serial_tl_0_out_ready),
    .io_outer_ser_out_valid       (serial_tl_0_out_valid),
    .io_outer_ser_out_bits_phit   (serial_tl_0_out_bits_phit),
    .io_inner_ser_0_in_ready      (_serdesser_io_ser_0_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_0_in_valid      (_phy_io_inner_ser_0_in_valid),
    .io_inner_ser_0_in_bits_flit  (_phy_io_inner_ser_0_in_bits_flit),
    .io_inner_ser_0_out_bits_flit (32'h0),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50, :186:27]
    .io_inner_ser_1_in_ready      (_serdesser_io_ser_1_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_1_in_valid      (_phy_io_inner_ser_1_in_valid),
    .io_inner_ser_1_in_bits_flit  (_phy_io_inner_ser_1_in_bits_flit),
    .io_inner_ser_1_out_ready     (_phy_io_inner_ser_1_out_ready),
    .io_inner_ser_1_out_valid     (_serdesser_io_ser_1_out_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_1_out_bits_flit (_serdesser_io_ser_1_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_2_in_ready      (_serdesser_io_ser_2_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_2_in_valid      (_phy_io_inner_ser_2_in_valid),
    .io_inner_ser_2_in_bits_flit  (_phy_io_inner_ser_2_in_bits_flit),
    .io_inner_ser_2_out_ready     (/* unused */),
    .io_inner_ser_2_out_valid     (1'h0),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28, generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50, :186:27]
    .io_inner_ser_2_out_bits_flit (32'h0),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50, :186:27]
    .io_inner_ser_3_in_ready      (_serdesser_io_ser_3_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_3_in_valid      (_phy_io_inner_ser_3_in_valid),
    .io_inner_ser_3_in_bits_flit  (_phy_io_inner_ser_3_in_bits_flit),
    .io_inner_ser_3_out_ready     (_phy_io_inner_ser_3_out_ready),
    .io_inner_ser_3_out_valid     (_serdesser_io_ser_3_out_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_3_out_bits_flit (_serdesser_io_ser_3_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_4_in_ready      (_serdesser_io_ser_4_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_4_in_valid      (_phy_io_inner_ser_4_in_valid),
    .io_inner_ser_4_in_bits_flit  (_phy_io_inner_ser_4_in_bits_flit),
    .io_inner_ser_4_out_ready     (/* unused */),
    .io_inner_ser_4_out_valid     (1'h0),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28, generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50, :186:27]
    .io_inner_ser_4_out_bits_flit (32'h0)	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50, :186:27]
  );	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:186:27]
  ResetCatchAndSync_d3 phy_io_outer_reset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (serial_tl_0_clock_in),
    .reset         (auto_clock_in_reset),
    .io_sync_reset (_phy_io_outer_reset_catcher_io_sync_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
endmodule

