// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLAToBeat_SerialRAM_a64d64s8k8z8c(	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
  input         clock,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
  input         reset,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
  output        io_protocol_ready,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input         io_protocol_valid,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input  [2:0]  io_protocol_bits_opcode,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input  [2:0]  io_protocol_bits_param,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input  [7:0]  io_protocol_bits_size,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input  [7:0]  io_protocol_bits_source,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input  [63:0] io_protocol_bits_address,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input  [7:0]  io_protocol_bits_mask,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input  [63:0] io_protocol_bits_data,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input         io_protocol_bits_corrupt,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  input         io_beat_ready,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  output        io_beat_valid,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  output [85:0] io_beat_bits_payload,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  output        io_beat_bits_head,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
  output        io_beat_bits_tail	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:40:14]
);

  wire [8:0]   _GEN;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:109:{45,69}]
  wire         _q_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [2:0]   _q_io_deq_bits_opcode;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [2:0]   _q_io_deq_bits_param;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [7:0]   _q_io_deq_bits_size;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [7:0]   _q_io_deq_bits_source;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [63:0]  _q_io_deq_bits_address;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [7:0]   _q_io_deq_bits_mask;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [63:0]  _q_io_deq_bits_data;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire         _q_io_deq_bits_corrupt;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  wire [266:0] _tail_beats1_decode_T = 267'hFFF << _q_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  reg  [8:0]   head_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire         head = head_counter == 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  wire [8:0]   tail_beats1 = _q_io_deq_bits_opcode[2] ? 9'h0 : ~(_tail_beats1_decode_T[11:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  reg  [8:0]   tail_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg          is_body;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:60:24]
  wire         _io_beat_bits_tail_T = _GEN == 9'h0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:109:{45,69}]
  wire         q_io_deq_ready = io_beat_ready & (is_body | _io_beat_bits_tail_T);	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:60:24, :62:{35,47}, :109:{45,69}]
  wire         io_beat_bits_head_0 = head & ~is_body;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:60:24, :64:{35,38}]
  wire         io_beat_bits_tail_0 = (tail_counter == 9'h1 | tail_beats1 == 9'h0) & (is_body | _io_beat_bits_tail_T);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :232:{25,33,43}, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:60:24, :65:{35,47}, :109:{45,69}]
  assign _GEN = {~(_q_io_deq_bits_opcode[2]), ~_q_io_deq_bits_mask};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17, :109:{45,49,69}]
  wire         _GEN_0 = io_beat_ready & _q_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
    if (reset) begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
      head_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      tail_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      is_body <= 1'h0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:60:24, :108:7]
    end
    else begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
      if (q_io_deq_ready & _q_io_deq_valid) begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17, :62:35, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        head_counter <= head ? (_q_io_deq_bits_opcode[2] ? 9'h0 : ~(_tail_beats1_decode_T[11:3])) : head_counter - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
        tail_counter <= tail_counter == 9'h0 ? tail_beats1 : tail_counter - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :230:28, :231:25, :236:21]
      end
      is_body <= ~(_GEN_0 & io_beat_bits_tail_0) & (_GEN_0 & io_beat_bits_head_0 | is_body);	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:60:24, :64:35, :65:35, :68:{22,44,54}, :69:{22,44,54}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
    initial begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
        `INIT_RANDOM_PROLOG_	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
        head_counter = _RANDOM[/*Zero width*/ 1'b0][8:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
        tail_counter = _RANDOM[/*Zero width*/ 1'b0][17:9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
        is_body = _RANDOM[/*Zero width*/ 1'b0][18];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:60:24, :108:7]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:108:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue1_TLBundleA_a64d64s8k8z8c q (	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (io_protocol_ready),
    .io_enq_valid        (io_protocol_valid),
    .io_enq_bits_opcode  (io_protocol_bits_opcode),
    .io_enq_bits_param   (io_protocol_bits_param),
    .io_enq_bits_size    (io_protocol_bits_size),
    .io_enq_bits_source  (io_protocol_bits_source),
    .io_enq_bits_address (io_protocol_bits_address),
    .io_enq_bits_mask    (io_protocol_bits_mask),
    .io_enq_bits_data    (io_protocol_bits_data),
    .io_enq_bits_corrupt (io_protocol_bits_corrupt),
    .io_deq_ready        (q_io_deq_ready),	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:62:35]
    .io_deq_valid        (_q_io_deq_valid),
    .io_deq_bits_opcode  (_q_io_deq_bits_opcode),
    .io_deq_bits_param   (_q_io_deq_bits_param),
    .io_deq_bits_size    (_q_io_deq_bits_size),
    .io_deq_bits_source  (_q_io_deq_bits_source),
    .io_deq_bits_address (_q_io_deq_bits_address),
    .io_deq_bits_mask    (_q_io_deq_bits_mask),
    .io_deq_bits_data    (_q_io_deq_bits_data),
    .io_deq_bits_corrupt (_q_io_deq_bits_corrupt)
  );	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17]
  assign io_beat_valid = _q_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17, :108:7]
  assign io_beat_bits_payload = is_body ? {13'h0, _q_io_deq_bits_mask, _q_io_deq_bits_data, _q_io_deq_bits_corrupt} : {_q_io_deq_bits_opcode, _q_io_deq_bits_param, _q_io_deq_bits_size, _q_io_deq_bits_source, _q_io_deq_bits_address};	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:47:17, :58:18, :60:24, :66:33, :108:7]
  assign io_beat_bits_head = io_beat_bits_head_0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:64:35, :108:7]
  assign io_beat_bits_tail = io_beat_bits_tail_0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:65:35, :108:7]
endmodule

